/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v4.4-dev-3015-gc0d0b1c4f6"
#endif /* AVUTIL_FFVERSION_H */
