language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make) && make -f Makefile.lite

matrix:
  include:
    - os: linux
      compiler: i586-mingw32msvc-gcc
      script: autoconf && ./configure --host=i586-mingw32msvc && make
    - os: linux
      compiler: '"clang -fsanitize=address"'
      script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)
    - os: linux
      compiler: '"clang -fsanitize=memory"'
      script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)

