// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_2sf= {
	locateFile: function(path, scriptDirectory) { return (typeof window.WASM_SEARCH_PATH == 'undefined') ? path : window.WASM_SEARCH_PATH + path; },
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_2sf["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_2sf);

var backend_ds = (function(Module) {var e;e||(e=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in e)e.hasOwnProperty(l)&&(k[l]=e[l]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var aa=!1,n=!1,q=!1,ba=!1;aa="object"===typeof window;n="function"===typeof importScripts;q="object"===typeof process&&"function"===typeof require&&!aa&&!n;ba=!aa&&!q&&!n;var r="";function ca(a){return e.locateFile?e.locateFile(a,r):r+a}
if(q){r=__dirname+"/";var da,fa;e.read=function(a,b){da||(da=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",
t);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(aa||n)n?
r=self.location.href:document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ha=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),u=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(l in k)k.hasOwnProperty(l)&&(e[l]=k[l]);k=void 0;function ia(a){var b=v;v=v+a+15&-16;return b}
function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},la=!1;function assert(a,b){a||t("Assertion failed: "+b)}var pa={stackSave:function(){x()},stackRestore:function(){y()},arrayToC:function(a){var b=ma(a.length);na.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=ma(c);oa(a,z,b,c)}return b}},qa={string:pa.stringToC,array:pa.arrayToC};
function A(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=z[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,z.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return ra(a)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var m=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|m;else{var p=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|m<<6|p}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}function ra(a){return ua(z,a)}
function oa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function va(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,na,z,wa,B;function xa(){e.HEAP8=na=new Int8Array(buffer);e.HEAP16=wa=new Int16Array(buffer);e.HEAP32=B=new Int32Array(buffer);e.HEAPU8=z=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=new Float64Array(buffer)}
var ya,v,za,Aa,Ba,Ca,Da,D;ya=v=Aa=Ba=Ca=Da=D=0;za=!1;e.reallocBuffer||(e.reallocBuffer=function(a){try{var b=na;var c=new ArrayBuffer(a);(new Int8Array(c)).set(b)}catch(d){return!1}return Ea(c)?c:!1});function Fa(){var a=e.usingWasm?65536:16777216,b=2147483648-a;if(B[D>>2]>b)return!1;var c=E;for(E=Math.max(E,16777216);E<B[D>>2];)536870912>=E?E=va(2*E,a):E=Math.min(va((3*E+2147483648)/4,a),b);a=e.reallocBuffer(E);if(!a||a.byteLength!=E)return E=c,!1;e.buffer=buffer=a;xa();return!0}var Ga;
try{Ga=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ga(new ArrayBuffer(4))}catch(a){Ga=function(b){return b.byteLength}}var Ha=e.TOTAL_STACK||5242880,E=e.TOTAL_MEMORY||268435456;E<Ha&&u("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+E+"! (TOTAL_STACK="+Ha+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:E/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(E),e.buffer=buffer);xa();function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Ia;"number"===typeof c?void 0===b.W?e.dynCall_v(c):e.dynCall_vi(c,b.W):c(void 0===b.W?null:b.W)}}}var Ja=[],Ka=[],La=[],Ma=[],Na=[],Oa=!1;
function Pa(){var a=e.preRun.shift();Ja.unshift(a)}var F=0,Qa=null,Ta=null;function Ua(){F++;e.monitorRunDependencies&&e.monitorRunDependencies(F)}function Va(){F--;e.monitorRunDependencies&&e.monitorRunDependencies(F);if(0==F&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ta)){var a=Ta;Ta=null;a()}}e.preloadedImages={};e.preloadedAudios={};function Wa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(C){t(C)}}function b(){return e.wasmBinary||!aa&&!n||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){m=a.exports;
if(m.memory){a=m.memory;var b=e.buffer;a.byteLength<b.byteLength&&u("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;xa()}e.asm=m;e.usingWasm=!0;Va()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){u("failed to asynchronously prepare wasm: "+a);t(a)})}if("object"!==typeof WebAssembly)return u("no native wasm support detected"),
!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return u("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Ua();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(N){return u("Module.instantiateWasm callback failed with error: "+N),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Wa(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d,
function(a){u("wasm streaming compile failed: "+a);u("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="2sf.wast",f="2sf.wasm",g="2sf.temp.asm.js";Wa(d)||(d=ca(d));Wa(f)||(f=ca(f));Wa(g)||(g=ca(g));var h={global:null,env:null,asm2wasm:ka,parent:e},m=null;e.asmPreload=e.asm;var p=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===w)var b=p(a);else a:{a=va(a,e.usingWasm?65536:16777216);var c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=
e.wasmMemory.buffer:null;break a}catch(ta){b=null;break a}b=void 0}return b};var w="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,
"no binaryen method succeeded.");return b}})();ya=1024;v=ya+207888;Ka.push({Ia:function(){Xa()}});e.STATIC_BASE=ya;e.STATIC_BUMP=207888;v+=16;function Ya(){return!!Ya.N}var Za=0,$a=[],G={};function ab(a){if(!a||G[a])return a;for(var b in G){var c=+b;if(G[c].ia===a)return c}return a}function ___cxa_free_exception(a){try{return bb(a)}catch(b){}}
function cb(){var a=Za;if(!a)return(db(0),0)|0;var b=G[a],c=b.type;if(!c)return(db(0),a)|0;var d=Array.prototype.slice.call(arguments);e.___cxa_is_pointer_type(c);eb||(eb=fb(4));B[eb>>2]=a;a=eb;for(var f=0;f<d.length;f++)if(d[f]&&e.___cxa_can_catch(d[f],c,a))return a=B[a>>2],b.ia=a,(db(d[f]),a)|0;a=B[a>>2];return(db(c),a)|0}
var eb,H={F:1,u:2,Fc:3,Bb:4,B:5,ha:6,Ua:7,Zb:8,s:9,ib:10,da:11,Pc:11,Ca:12,S:13,ub:14,lc:15,T:16,ea:17,Qc:18,V:19,fa:20,I:21,h:22,Ub:23,Ba:24,C:25,Mc:26,vb:27,hc:28,M:29,Cc:30,Nb:31,vc:32,rb:33,zc:34,cc:42,yb:43,jb:44,Eb:45,Fb:46,Gb:47,Mb:48,Nc:49,Xb:50,Db:51,ob:35,$b:37,$a:52,cb:53,Rc:54,Vb:55,eb:56,fb:57,pb:35,gb:59,jc:60,Yb:61,Jc:62,ic:63,dc:64,ec:65,Bc:66,ac:67,Xa:68,Gc:69,kb:70,wc:71,Pb:72,sb:73,bb:74,qc:76,ab:77,Ac:78,Hb:79,Ib:80,Lb:81,Kb:82,Jb:83,kc:38,ga:39,Qb:36,U:40,rc:95,uc:96,nb:104,Wb:105,
Ya:97,yc:91,oc:88,fc:92,Dc:108,mb:111,Va:98,lb:103,Tb:101,Rb:100,Kc:110,wb:112,xb:113,Ab:115,Za:114,qb:89,Ob:90,xc:93,Ec:94,Wa:99,Sb:102,Cb:106,mc:107,Lc:109,Oc:87,tb:122,Hc:116,pc:95,bc:123,zb:84,sc:75,hb:125,nc:131,tc:130,Ic:86},gb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function hb(a){e.___errno_location&&(B[e.___errno_location()>>2]=a);return a}
function ib(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function jb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ib(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function kb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function lb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function mb(){var a=Array.prototype.slice.call(arguments,0);return jb(a.join("/"))}function I(a,b){return jb(a+"/"+b)}
function nb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ib(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ob=[];function pb(a,b){ob[a]={input:[],output:[],H:b};qb(a,rb)}
var rb={open:function(a){var b=ob[a.node.rdev];if(!b)throw new J(H.V);a.tty=b;a.seekable=!1},close:function(a){a.tty.H.flush(a.tty)},flush:function(a){a.tty.H.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.H.ta)throw new J(H.ha);for(var f=0,g=0;g<d;g++){try{var h=a.tty.H.ta(a.tty)}catch(m){throw new J(H.B);}if(void 0===h&&0===f)throw new J(H.da);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.H.aa)throw new J(H.ha);
for(var f=0;f<d;f++)try{a.tty.H.aa(a.tty,b[c+f])}catch(g){throw new J(H.B);}d&&(a.node.timestamp=Date.now());return f}},tb={ta:function(a){if(!a.input.length){var b=null;if(q){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=sb(b)}return a.input.shift()},aa:function(a,b){null===b||10===b?(ha(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(ua(a.output,0)),a.output=[])}},ub={aa:function(a,b){null===b||10===b?(u(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&
(u(ua(a.output,0)),a.output=[])}},K={m:null,j:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(H.F);K.m||(K.m={dir:{node:{o:K.c.o,i:K.c.i,lookup:K.c.lookup,J:K.c.J,rename:K.c.rename,unlink:K.c.unlink,rmdir:K.c.rmdir,readdir:K.c.readdir,symlink:K.c.symlink},stream:{A:K.f.A}},file:{node:{o:K.c.o,i:K.c.i},stream:{A:K.f.A,read:K.f.read,write:K.f.write,ja:K.f.ja,wa:K.f.wa,za:K.f.za}},link:{node:{o:K.c.o,i:K.c.i,readlink:K.c.readlink},
stream:{}},na:{node:{o:K.c.o,i:K.c.i},stream:vb}});c=wb(a,b,c,d);L(c.mode)?(c.c=K.m.dir.node,c.f=K.m.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=K.m.file.node,c.f=K.m.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=K.m.link.node,c.f=K.m.link.stream):8192===(c.mode&61440)&&(c.c=K.m.na.node,c.f=K.m.na.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ja:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Uc:function(a){return a.b?a.b.subarray?
a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},pa:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=K.Ja(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Pa:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));c&&
a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.D=4096;b.blocks=Math.ceil(b.size/b.D);return b},
i:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Pa(a,b.size)},lookup:function(){throw xb[H.u];},J:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=M(b,c)}catch(g){}if(d)for(var f in d.b)throw new J(H.ga);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=M(a,b),d;for(d in c.b)throw new J(H.ga);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(H.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}K.pa(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},A:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new J(H.h);return b},ja:function(a,b,c){K.pa(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},wa:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new J(H.V);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=fb(d);if(!d)throw new J(H.Ca);b.set(c,d)}else a=!1,d=c.byteOffset;return{Oa:d,Sc:a}},za:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new J(H.V);if(f&2)return 0;K.f.write(a,b,0,d,c,!1);return 0}}},O={P:!1,Sa:function(){O.P=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);O.qa={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ka:function(a){return Buffer.N?Buffer.from(a):new Buffer(a)},j:function(a){assert(q);return O.createNode(null,"/",O.sa(a.$.root),0)},createNode:function(a,b,c){if(!L(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new J(H.h);a=wb(a,b,c);a.c=O.c;a.f=O.f;return a},sa:function(a){try{var b=fs.lstatSync(a);O.P&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new J(H[c.code]);}return b.mode},l:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.j.$.root);b.reverse();return mb.apply(null,b)},Ha:function(a){a&=-2656257;var b=0,c;for(c in O.qa)a&c&&(b|=O.qa[c],a^=c);if(a)throw new J(H.h);return b},c:{o:function(a){a=O.l(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}O.P&&!b.D&&(b.D=4096);O.P&&!b.blocks&&(b.blocks=(b.size+b.D-1)/b.D|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,D:b.D,blocks:b.blocks}},i:function(a,b){var c=O.l(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new J(H[d.code]);}},lookup:function(a,b){var c=I(O.l(a),b);c=O.sa(c);return O.createNode(a,b,c)},J:function(a,b,c,d){a=O.createNode(a,b,c,d);b=O.l(a);try{L(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new J(H[f.code]);}return a},rename:function(a,b,c){a=O.l(a);b=I(O.l(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new J(H[d.code]);}},unlink:function(a,b){a=I(O.l(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}},rmdir:function(a,b){a=I(O.l(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}},readdir:function(a){a=O.l(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new J(H[b.code]);}},symlink:function(a,
b,c){a=I(O.l(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new J(H[d.code]);}},readlink:function(a){var b=O.l(a);try{return b=fs.readlinkSync(b),b=yb.relative(yb.resolve(a.j.$.root),b)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}}},f:{open:function(a){var b=O.l(a.node);try{32768===(a.node.mode&61440)&&(a.L=fs.openSync(b,O.Ha(a.flags)))}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.L&&fs.closeSync(a.L)}catch(b){if(!b.code)throw b;
throw new J(H[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.L,O.ka(b.buffer),c,d,f)}catch(g){throw new J(H[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.L,O.ka(b.buffer),c,d,f)}catch(g){throw new J(H[g.code]);}},A:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.L).size}catch(d){throw new J(H[d.code]);}if(0>b)throw new J(H.h);return b}}};v+=16;v+=16;v+=16;
var zb=null,Ab={},P=[],Bb=1,Q=null,Cb=!0,R={},J=null,xb={};
function S(a,b){a=nb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ra:!0,ba:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ba)throw new J(H.U);a=ib(a.split("/").filter(function(a){return!!a}),!1);var f=zb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=M(f,a[d]);c=I(c,a[d]);f.K&&(!g||g&&b.ra)&&(f=f.K.root);if(!g||b.X)for(g=0;40960===(f.mode&61440);)if(f=Db(c),c=nb(kb(c),f),f=S(c,{ba:b.ba}).node,40<g++)throw new J(H.U);}return{path:c,node:f}}
function T(a){for(var b;;){if(a===a.parent)return a=a.j.ya,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function Fb(a){var b=Eb(a.parent.id,a.name);a.G=Q[b];Q[b]=a}function M(a,b){var c;if(c=(c=Gb(a,"x"))?c:a.c.lookup?0:H.S)throw new J(c,a);for(c=Q[Eb(a.id,b)];c;c=c.G){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function wb(a,b,c,d){Hb||(Hb=function(a,b,c,d){a||(a=this);this.parent=a;this.j=a.j;this.K=null;this.id=Bb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Hb.prototype={},Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ma:{get:function(){return L(this.mode)}},La:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Hb(a,b,c,d);Fb(a);return a}function L(a){return 16384===(a&61440)}var Ib={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(Cb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return H.S}else return H.S;return 0}
function Kb(a,b){try{return M(a,b),H.ea}catch(c){}return Gb(a,"wx")}function Lb(a){var b=4096;for(a=a||0;a<=b;a++)if(!P[a])return a;throw new J(H.Ba);}function Mb(a,b){Nb||(Nb=function(){},Nb.prototype={},Object.defineProperties(Nb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Nb,d;for(d in a)c[d]=a[d];a=c;b=Lb(b);a.fd=b;return P[b]=a}var vb={open:function(a){a.f=Ab[a.node.rdev].f;a.f.open&&a.f.open(a)},A:function(){throw new J(H.M);}};
function qb(a,b){Ab[a]={f:b}}function Ob(a,b){var c="/"===b,d=!b;if(c&&zb)throw new J(H.T);if(!c&&!d){var f=S(b,{ra:!1});b=f.path;f=f.node;if(f.K)throw new J(H.T);if(!L(f.mode))throw new J(H.fa);}b={type:a,$:{},ya:b,Na:[]};a=a.j(b);a.j=b;b.root=a;c?zb=a:f&&(f.K=b,f.j&&f.j.Na.push(b))}function Pb(a,b,c){var d=S(a,{parent:!0}).node;a=lb(a);if(!a||"."===a||".."===a)throw new J(H.h);var f=Kb(d,a);if(f)throw new J(f);if(!d.c.J)throw new J(H.F);return d.c.J(d,a,b,c)}
function U(a,b){return Pb(a,(void 0!==b?b:511)&1023|16384,0)}function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Pb(a,b|8192,c)}function Rb(a,b){if(!nb(a))throw new J(H.u);var c=S(b,{parent:!0}).node;if(!c)throw new J(H.u);b=lb(b);var d=Kb(c,b);if(d)throw new J(d);if(!c.c.symlink)throw new J(H.F);return c.c.symlink(c,b,a)}
function Sb(a){var b=S(a,{parent:!0}).node,c=lb(a),d=M(b,c);a:{try{var f=M(b,c)}catch(h){f=h.v;break a}var g=Gb(b,"wx");f=g?g:L(f.mode)?H.I:0}if(f)throw new J(f);if(!b.c.unlink)throw new J(H.F);if(d.K)throw new J(H.T);try{R.willDeletePath&&R.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Eb(d.parent.id,d.name);if(Q[b]===d)Q[b]=d.G;else for(b=Q[b];b;){if(b.G===d){b.G=d.G;break}b=b.G}try{if(R.onDeletePath)R.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Db(a){a=S(a).node;if(!a)throw new J(H.u);if(!a.c.readlink)throw new J(H.h);return nb(T(a.parent),a.c.readlink(a))}function Tb(a,b){var c;"string"===typeof a?c=S(a,{X:!0}).node:c=a;if(!c.c.i)throw new J(H.F);c.c.i(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function V(a,b,c,d){if(""===a)throw new J(H.u);if("string"===typeof b){var f=Ib[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=jb(a);try{g=S(a,{X:!(b&131072)}).node}catch(p){}}f=!1;if(b&64)if(g){if(b&128)throw new J(H.ea);}else g=Pb(a,c,0),f=!0;if(!g)throw new J(H.u);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!L(g.mode))throw new J(H.fa);if(!f){var h=g?40960===(g.mode&61440)?H.U:
L(g.mode)&&("r"!==Jb(b)||b&512)?H.I:Gb(g,Jb(b)):H.u;if(h)throw new J(h);}if(b&512){c=g;var m;"string"===typeof c?m=S(c,{X:!0}).node:m=c;if(!m.c.i)throw new J(H.F);if(L(m.mode))throw new J(H.I);if(32768!==(m.mode&61440))throw new J(H.h);if(c=Gb(m,"w"))throw new J(c);m.c.i(m,{size:0,timestamp:Date.now()})}b&=-641;d=Mb({node:g,path:T(g),flags:b,seekable:!0,position:0,f:g.f,Ta:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(Ub||(Ub={}),a in Ub||(Ub[a]=1,h("read file: "+a)));try{R.onOpenFile&&
(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),R.onOpenFile(a,h))}catch(p){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d}function Vb(a){if(null===a.fd)throw new J(H.s);a.Y&&(a.Y=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{P[a.fd]=null}a.fd=null}function Wb(a,b,c){if(null===a.fd)throw new J(H.s);if(!a.seekable||!a.f.A)throw new J(H.M);a.position=a.f.A(a,b,c);a.Ta=[]}
function Xb(a,b,c,d,f,g){if(0>d||0>f)throw new J(H.h);if(null===a.fd)throw new J(H.s);if(0===(a.flags&2097155))throw new J(H.s);if(L(a.node.mode))throw new J(H.I);if(!a.f.write)throw new J(H.h);a.flags&1024&&Wb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new J(H.M);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&R.onWriteToFile)R.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+m.message)}return b}
function Yb(){J||(J=function(a,b){this.node=b;this.Ra=function(a){this.v=a;for(var b in H)if(H[b]===a){this.code=b;break}};this.Ra(a);this.message=gb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},J.prototype=Error(),J.prototype.constructor=J,[H.u].forEach(function(a){xb[a]=new J(a);xb[a].stack="<generic error, no stack>"}))}var Zb;function $b(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function ac(a,b,c,d){a=I("string"===typeof a?a:T(a),b);return U(a,$b(c,d))}function bc(a,b){a="string"===typeof a?a:T(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=I(a,c);try{U(d)}catch(f){}a=d}}return d}function cc(a,b,c,d){a=I("string"===typeof a?a:T(a),b);c=$b(c,d);return Pb(a,(void 0!==c?c:438)&4095|32768,0)}
function dc(a,b,c,d,f,g){a=b?I("string"===typeof a?a:T(a),b):a;d=$b(d,f);f=Pb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Tb(f,d|146);a=V(f,"w");Xb(a,c,0,c.length,0,g);Vb(a);Tb(f,d)}return f}
function W(a,b,c,d){a=I("string"===typeof a?a:T(a),b);b=$b(!!c,!!d);W.va||(W.va=64);var f=W.va++<<8|0;qb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var m=c()}catch(Sa){throw new J(H.B);}if(void 0===m&&0===g)throw new J(H.da);if(null===m||void 0===m)break;g++;b[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(C){throw new J(H.B);}f&&(a.node.timestamp=
Date.now());return g}});return Qb(a,b,f)}function ec(a,b,c){a=I("string"===typeof a?a:T(a),b);return Rb(c,a)}
function fc(a){if(a.La||a.Ma||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=sb(e.read(a.url)),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||hb(H.B);return b}
function hc(a,b,c,d,f){function g(){this.Z=!1;this.O=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.ua(a/this.chunkSize|0)[b]}};g.prototype.Qa=function(a){this.ua=a};g.prototype.la=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Qa(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.O[a]){var m=h.O;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==g&&p.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");p.overrideMimeType&&
p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):sb(p.responseText||"");m[a]=d}if("undefined"===typeof h.O[a])throw Error("doXHR failed!");return h.O[a]});if(a||!b)g=b=1,g=b=this.ua(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ea=b;this.Da=g;this.Z=!0};if("undefined"!==
typeof XMLHttpRequest){if(!n)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Z||this.la();return this.Ea}},chunkSize:{get:function(){this.Z||this.la();return this.Da}}});var m=void 0}else m=c,h=void 0;var p=cc(a,b,d,f);h?p.b=h:m&&(p.b=null,p.url=m);Object.defineProperties(p,{g:{get:function(){return this.b.length}}});var w={};Object.keys(p.f).forEach(function(a){var b=
p.f[a];w[a]=function(){if(!fc(p))throw new J(H.B);return b.apply(null,arguments)}});w.read=function(a,b,c,d,f){if(!fc(p))throw new J(H.B);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};p.f=w;return p}
function ic(a,b,c,d,f,g,h,m,p,w){function C(c){function C(c){w&&w();m||dc(a,b,c,d,f,p);g&&g();Va()}var N=!1;e.preloadPlugins.forEach(function(a){!N&&a.canHandle(ea)&&(a.handle(c,ea,C,function(){h&&h();Va()}),N=!0)});N||C(c)}Browser.Vc();var ea=b?nb(I(a,b)):a;Ua();"string"==typeof c?Browser.Tc(c,function(a){C(a)},h):C(c)}var FS={},Hb,Nb,Ub,X=0;function Y(){X+=4;return B[X-4>>2]}function Z(){var a=P[Y()];if(!a)throw new J(H.s);return a}Yb();Q=Array(4096);Ob(K,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");qb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Qb("/dev/null",259);pb(1280,tb);pb(1536,ub);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else q?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){t("random_device")};W("/dev","random",b);W("/dev","urandom",b);U("/dev/shm");U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");
Ob({j:function(){var a=wb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=P[+c];if(!b)throw new J(H.s);a={parent:null,j:{ya:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ka.unshift(function(){if(!e.noFSInit&&!Zb){assert(!Zb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Zb=!0;Yb();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?W("/dev","stdin",e.stdin):Rb("/dev/tty","/dev/stdin");e.stdout?W("/dev","stdout",null,e.stdout):Rb("/dev/tty","/dev/stdout");e.stderr?W("/dev","stderr",null,e.stderr):Rb("/dev/tty1","/dev/stderr");var a=
V("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=V("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=V("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});La.push(function(){Cb=!1});Ma.push(function(){Zb=!1;var a=e._fflush;a&&a(0);for(a=0;a<P.length;a++){var b=P[a];b&&Vb(b)}});e.FS_createFolder=ac;e.FS_createPath=bc;e.FS_createDataFile=dc;e.FS_createPreloadedFile=ic;e.FS_createLazyFile=hc;e.FS_createLink=ec;
e.FS_createDevice=W;e.FS_unlink=Sb;Ka.unshift(function(){});Ma.push(function(){});if(q){var fs=require("fs"),yb=require("path");O.Sa()}D=ia(4);Aa=Ba=ja(v);Ca=Aa+Ha;Da=ja(Ca);B[D>>2]=Da;za=!0;function sb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}b=Array(b+1);a=oa(a,b,0,b.length);b.length=a;return b}e.wasmTableSize=1132;e.wasmMaxTableSize=1132;
e.Fa={};
e.Ga={abort:t,enlargeMemory:Fa,getTotalMemory:function(){return E},abortOnCannotGrowMemory:function(){t("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+E+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},invoke_ii:function(a,b){var c=x();try{return e.dynCall_ii(a,b)}catch(d){y(c);if("number"!==
typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_iiii:function(a,b,c,d){var f=x();try{return e.dynCall_iiii(a,b,c,d)}catch(g){y(f);if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},invoke_v:function(a){var b=x();try{e.dynCall_v(a)}catch(c){y(b);if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},invoke_vi:function(a,b){var c=x();try{e.dynCall_vi(a,b)}catch(d){y(c);if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_vii:function(a,b,c){var d=x();
try{e.dynCall_vii(a,b,c)}catch(f){y(d);if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},invoke_viii:function(a,b,c,d){var f=x();try{e.dynCall_viii(a,b,c,d)}catch(g){y(f);if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},invoke_viiii:function(a,b,c,d,f){var g=x();try{e.dynCall_viiii(a,b,c,d,f)}catch(h){y(g);if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},___assert_fail:function(a,b,c,d){t("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?
A(d):"unknown function"])},___cxa_allocate_exception:function(a){return fb(a)},___cxa_begin_catch:function(a){var b=G[a];b&&!b.ma&&(b.ma=!0,Ya.N--);b&&(b.Aa=!1);$a.push(a);(b=ab(a))&&G[b].R++;return a},___cxa_end_catch:function(){e.setThrew(0);var a=$a.pop();if(a){if(a=ab(a)){var b=G[a];assert(0<b.R);b.R--;0!==b.R||b.Aa||(b.oa&&e.dynCall_vi(b.oa,a),delete G[a],___cxa_free_exception(a))}Za=0}},___cxa_find_matching_catch_2:function(){return cb.apply(null,arguments)},___cxa_find_matching_catch_3:function(){return cb.apply(null,
arguments)},___cxa_free_exception:___cxa_free_exception,___cxa_throw:function(a,b,c){G[a]={Oa:a,ia:a,type:b,oa:c,R:0,ma:!1,Aa:!1};Za=a;"uncaught_exception"in Ya?Ya.N++:Ya.N=1;throw a;},___lock:function(){},___resumeException:function(a){Za||(Za=a);throw a;},___setErrNo:hb,___syscall140:function(a,b){X=b;try{var c=Z();Y();var d=Y(),f=Y(),g=Y();Wb(c,d,g);B[f>>2]=c.position;c.Y&&0===d&&0===g&&(c.Y=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof J||t(h),-h.v}},___syscall145:function(a,
b){X=b;try{var c=Z(),d=Y();a:{var f=Y();for(b=a=0;b<f;b++){var g=B[d+(8*b+4)>>2],h=c,m=B[d+8*b>>2],p=g,w=void 0,C=na;if(0>p||0>w)throw new J(H.h);if(null===h.fd)throw new J(H.s);if(1===(h.flags&2097155))throw new J(H.s);if(L(h.node.mode))throw new J(H.I);if(!h.f.read)throw new J(H.h);var ea="undefined"!==typeof w;if(!ea)w=h.position;else if(!h.seekable)throw new J(H.M);var Sa=h.f.read(h,C,m,p,w);ea||(h.position+=Sa);var ta=Sa;if(0>ta){var N=-1;break a}a+=ta;if(ta<g)break}N=a}return N}catch(Ra){return"undefined"!==
typeof FS&&Ra instanceof J||t(Ra),-Ra.v}},___syscall146:function(a,b){X=b;try{var c=Z(),d=Y();a:{var f=Y();for(b=a=0;b<f;b++){var g=Xb(c,na,B[d+8*b>>2],B[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(m){return"undefined"!==typeof FS&&m instanceof J||t(m),-m.v}},___syscall221:function(a,b){X=b;try{var c=Z();switch(Y()){case 0:var d=Y();return 0>d?-H.h:V(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Y(),c.flags|=d,0;case 12:case 12:return d=
Y(),wa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-H.h;case 9:return hb(H.h),-1;default:return-H.h}}catch(f){return"undefined"!==typeof FS&&f instanceof J||t(f),-f.v}},___syscall5:function(a,b){X=b;try{var c=A(Y()),d=Y(),f=Y();return V(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof J||t(g),-g.v}},___syscall54:function(a,b){X=b;try{var c=Z(),d=Y();switch(d){case 21509:case 21505:return c.tty?0:-H.C;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-H.C;case 21519:if(!c.tty)return-H.C;var f=Y();return B[f>>2]=0;case 21520:return c.tty?-H.h:-H.C;case 21531:a=f=Y();if(!c.f.Ka)throw new J(H.C);return c.f.Ka(c,d,a);case 21523:return c.tty?0:-H.C;case 21524:return c.tty?0:-H.C;default:t("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof FS&&g instanceof J||t(g),-g.v}},___syscall6:function(a,b){X=b;try{var c=Z();Vb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof J||t(d),-d.v}},___unlock:function(){},_ems_request_file:function(a){var b=
window.ScriptNodePlayer.getInstance();if(b.isReady())return b._fileRequestCallback(a);window.console.log("error: ems_request_file not ready")},_emscripten_memcpy_big:function(a,b,c){z.set(z.subarray(b,b+c),a);return a},DYNAMICTOP_PTR:D,STACKTOP:Ba};var jc=e.asm(e.Fa,e.Ga,buffer);e.asm=jc;var Xa=e.__GLOBAL__sub_I_twosfplug_cpp=function(){return e.asm.__GLOBAL__sub_I_twosfplug_cpp.apply(null,arguments)};e.___cxa_can_catch=function(){return e.asm.___cxa_can_catch.apply(null,arguments)};
e.___cxa_is_pointer_type=function(){return e.asm.___cxa_is_pointer_type.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};var Ea=e._emscripten_replace_memory=function(){return e.asm._emscripten_replace_memory.apply(null,arguments)};e._emu_compute_audio_samples=function(){return e.asm._emu_compute_audio_samples.apply(null,arguments)};e._emu_get_audio_buffer=function(){return e.asm._emu_get_audio_buffer.apply(null,arguments)};
e._emu_get_audio_buffer_length=function(){return e.asm._emu_get_audio_buffer_length.apply(null,arguments)};e._emu_get_current_position=function(){return e.asm._emu_get_current_position.apply(null,arguments)};e._emu_get_max_position=function(){return e.asm._emu_get_max_position.apply(null,arguments)};e._emu_get_sample_rate=function(){return e.asm._emu_get_sample_rate.apply(null,arguments)};e._emu_get_track_info=function(){return e.asm._emu_get_track_info.apply(null,arguments)};
e._emu_load_file=function(){return e.asm._emu_load_file.apply(null,arguments)};e._emu_seek_position=function(){return e.asm._emu_seek_position.apply(null,arguments)};e._emu_set_boost=function(){return e.asm._emu_set_boost.apply(null,arguments)};e._emu_set_subsong=function(){return e.asm._emu_set_subsong.apply(null,arguments)};e._emu_teardown=function(){return e.asm._emu_teardown.apply(null,arguments)};
var bb=e._free=function(){return e.asm._free.apply(null,arguments)},fb=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},db=e.setTempRet0=function(){return e.asm.setTempRet0.apply(null,arguments)};e.setThrew=function(){return e.asm.setThrew.apply(null,arguments)};var ma=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)},y=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},x=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};
e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};
e.asm=jc;e.ccall=function(a,b,c,d){var f=e["_"+a];assert(f,"Cannot call unknown function "+a+", make sure it is exported");var g=[];a=0;if(d)for(var h=0;h<d.length;h++){var m=qa[c[h]];m?(0===a&&(a=x()),g[h]=m(d[h])):g[h]=d[h]}c=f.apply(null,g);c="string"===b?A(c):"boolean"===b?!!c:c;0!==a&&y(a);return c};e.getMemory=function(a){if(za)if(Oa)var b=fb(a);else b=B[D>>2],a=b+a+15&-16,B[D>>2]=a,a>=E&&!Fa()&&(B[D>>2]=b,b=0);else b=ia(a);return b};e.Pointer_stringify=A;e.UTF8ToString=ra;
e.addRunDependency=Ua;e.removeRunDependency=Va;e.FS_createFolder=ac;e.FS_createPath=bc;e.FS_createDataFile=dc;e.FS_createPreloadedFile=ic;e.FS_createLazyFile=hc;e.FS_createLink=ec;e.FS_createDevice=W;e.FS_unlink=Sb;Ta=function kc(){e.calledRun||lc();e.calledRun||(Ta=kc)};
function lc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!la)){Oa||(Oa=!0,Ia(Ka));Ia(La);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Na.unshift(a)}Ia(Na)}}if(!(0<F)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Pa();Ia(Ja);0<F||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=lc;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ha(a),u(a),a=JSON.stringify(a)):a="";la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;lc();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_2sf);
/*
 2sf_adapter.js: Adapts "2SF decoder" backend to generic WebAudio/ScriptProcessor player.

    version 1.1
 	copyright (C) 2019-2023 Juergen Wothke


 note: "2SF decoder" seems to be a SLOW implementation and on my machine Chrome sporadically
 prints console warnings that audioprocess takes too long (e.g. 150ms for 1024 samples! which
 SHOULD calculate in less than 20ms! this might just be a Chrome issue though)


 LICENSE

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2.1 of the License, or (at
 your option) any later version. This library is distributed in the hope
 that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
*/

class DsBackendAdapter extends EmsHEAP16BackendAdapter {
	constructor()
	{
		super(backend_ds.Module, 2, new SimpleFileMapper(backend_ds.Module));

		this.ensureReadyNotification();
	}

	loadMusicData(sampleRate, path, filename, data, options)
	{
		filename = this._getFilename(path, filename);

		let ret = this.Module.ccall('emu_load_file', 'number',
							['string', 'number', 'number', 'number', 'number', 'number'],
							[ filename, 0, 0, ScriptNodePlayer.getWebAudioSampleRate(), -999, false]);

		if (ret == 0)
		{
			this._setupOutputResampling(sampleRate);
		}
		return ret;
	}

	evalTrackOptions(options)
	{
		super.evalTrackOptions(options);

		let boostVolume = (options && options.boostVolume) ? options.boostVolume : 0;
		this.Module.ccall('emu_set_boost', 'number', ['number'], [boostVolume]);

		// no subsongs in this format
		return 0;
	}

	getSongInfoMeta()
	{
		return {
			title: String,
			artist: String,
			game: String,
			year: String,
			genre: String,
			copyright: String,
			psfby: String
		};
	}

	updateSongInfo(filename)
	{
		let result = this._songInfo;
		
		let numAttr = 7;
		let ret = this.Module.ccall('emu_get_track_info', 'number');

		let array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);
		result.title = this.Module.Pointer_stringify(array[0]);
		if (!result.title.length) result.title = this._makeTitleFromPath(filename);

		result.artist = this.Module.Pointer_stringify(array[1]);
		result.game = this.Module.Pointer_stringify(array[2]);
		result.year = this.Module.Pointer_stringify(array[3]);
		result.genre = this.Module.Pointer_stringify(array[4]);
		result.copyright = this.Module.Pointer_stringify(array[5]);
		result.psfby = this.Module.Pointer_stringify(array[6]);
	}
};
