// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_ZXTUNE= {
	locateFile: function(path, scriptDirectory) { return (typeof window.WASM_SEARCH_PATH == 'undefined') ? path : window.WASM_SEARCH_PATH + path; },
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_ZXTUNE["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_ZXTUNE);

var backend_ZxTune = (function(Module) {var d;d||(d=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in d)d.hasOwnProperty(k)&&(aa[k]=d[k]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var ba=!1,m=!1,p=!1,ca=!1;ba="object"===typeof window;m="function"===typeof importScripts;p="object"===typeof process&&"function"===typeof require&&!ba&&!m;ca=!ba&&!p&&!m;var q="";function da(a){return d.locateFile?d.locateFile(a,q):q+a}
if(p){q=__dirname+"/";var ea,fa;d.read=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);a=ea.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=d);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",
u);d.quit=function(a){process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)});else if(ba||m)m?
q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",d.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==
e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};var ha=d.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=d.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(k in aa)aa.hasOwnProperty(k)&&(d[k]=aa[k]);aa=void 0;function ia(a){var b=w;w=w+a+15&-16;return b}
function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},la=!1;function assert(a,b){a||u("Assertion failed: "+b)}var pa={stackSave:function(){x()},stackRestore:function(){y()},arrayToC:function(a){var b=ma(a.length);C.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=ma(c);oa(a,D,b,c)}return b}},qa={string:pa.stringToC,array:pa.arrayToC};
function ra(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var e=("function"===typeof E?E:ia)(Math.max(c,1));if(b){a=e;assert(0==(e&3));for(b=e+(c&-4);a<b;a+=4)F[a>>2]=0;for(b=e+c;a<b;)C[a++>>0]=0;return e}a.subarray||a.slice?D.set(a,e):D.set(new Uint8Array(a),e);return e}function sa(a){if(ta)if(ua)var b=E(a);else{b=F[va>>2];a=b+a+15&-16;F[va>>2]=a;if(a=a>=G)wa(),a=!0;a&&(F[va>>2]=b,b=0)}else b=ia(a);return b}
function H(a,b){if(0===b||!a)return"";for(var c=0,e,f=0;;){e=D[a+f>>0];c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,D.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return xa(D,a)}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(c="";;){var e=a[b++];if(!e)return c;if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;if(224==(e&240))e=(e&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|f<<12|g<<6|h;else{var l=a[b++]&63;if(248==(e&252))e=(e&3)<<24|f<<18|g<<12|h<<6|l;else{var n=a[b++]&63;e=(e&1)<<30|f<<24|g<<18|h<<12|l<<6|n}}}65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}}
function oa(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=e)break;b[c++]=h}else{if(2047>=h){if(c+1>=e)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=e)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=e)break;b[c++]=248|h>>24}else{if(c+5>=e)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function za(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,C,D,Aa,F;
function Ba(){d.HEAP8=C=new Int8Array(buffer);d.HEAP16=Aa=new Int16Array(buffer);d.HEAP32=F=new Int32Array(buffer);d.HEAPU8=D=new Uint8Array(buffer);d.HEAPU16=new Uint16Array(buffer);d.HEAPU32=new Uint32Array(buffer);d.HEAPF32=new Float32Array(buffer);d.HEAPF64=new Float64Array(buffer)}var Ca,w,ta,Da,Ea,Fa,Ga,va;Ca=w=Da=Ea=Fa=Ga=va=0;ta=!1;
function wa(){u("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ha=d.TOTAL_STACK||5242880,G=d.TOTAL_MEMORY||33554432;G<Ha&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK="+Ha+")");
d.buffer?buffer=d.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(d.wasmMemory=new WebAssembly.Memory({initial:G/65536,maximum:G/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(G),d.buffer=buffer);Ba();function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.b;"number"===typeof c?void 0===b.ea?d.dynCall_v(c):d.dynCall_vi(c,b.ea):c(void 0===b.ea?null:b.ea)}}}var Ja=[],Ka=[],La=[],Ma=[],Na=[],ua=!1;
function Oa(){var a=d.preRun.shift();Ja.unshift(a)}var Pa=0,Qa=null,Ra=null;function Sa(){Pa++;d.monitorRunDependencies&&d.monitorRunDependencies(Pa)}function Ta(){Pa--;d.monitorRunDependencies&&d.monitorRunDependencies(Pa);if(0==Pa&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ra)){var a=Ra;Ra=null;a()}}d.preloadedImages={};d.preloadedAudios={};
function Ua(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(t){u(t)}}function b(){return d.wasmBinary||!ba&&!m||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){l=a.exports;
if(l.memory){a=l.memory;var b=d.buffer;a.byteLength<b.byteLength&&v("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);d.buffer=buffer=a;Ba()}d.asm=l;d.usingWasm=!0;Ta()}function e(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+a);u(a)})}if("object"!==typeof WebAssembly)return v("no native wasm support detected"),
!1;if(!(d.wasmMemory instanceof WebAssembly.Memory))return v("no native wasm Memory in use"),!1;a.memory=d.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Sa();if(d.instantiateWasm)try{return d.instantiateWasm(h,c)}catch(K){return v("Module.instantiateWasm callback failed with error: "+K),!1}d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ua(f)||"function"!==typeof fetch?g(e):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(e,
function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");g(e)});return{}}var e="zxtune.wast",f="zxtune.wasm",g="zxtune.temp.asm.js";Ua(e)||(e=da(e));Ua(f)||(f=da(f));Ua(g)||(g=da(g));var h={global:null,env:null,asm2wasm:ka,parent:d},l=null;d.asmPreload=d.asm;var n=d.reallocBuffer;d.reallocBuffer=function(a){if("asmjs"===r)var b=n(a);else a:{var c=d.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=d.buffer.byteLength;if(d.usingWasm)try{b=-1!==d.wasmMemory.grow((a-
c)/65536)?d.buffer=d.wasmMemory.buffer:null;break a}catch(z){b=null;break a}b=void 0}return b};var r="";d.asm=function(a,b){if(!b.table){a=d.wasmTableSize;void 0===a&&(a=1024);var e=d.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);d.wasmTable=b.table}b.memoryBase||(b.memoryBase=d.STATIC_BASE);b.tableBase||(b.tableBase=
0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();Ca=1024;w=Ca+1307520;
Ka.push({b:function(){Va()}},{b:function(){Wa()}},{b:function(){Xa()}},{b:function(){Ya()}},{b:function(){Za()}},{b:function(){$a()}},{b:function(){ab()}},{b:function(){bb()}},{b:function(){cb()}},{b:function(){db()}},{b:function(){eb()}},{b:function(){fb()}},{b:function(){gb()}},{b:function(){hb()}},{b:function(){ib()}},{b:function(){jb()}},{b:function(){kb()}},{b:function(){lb()}},{b:function(){mb()}},{b:function(){nb()}},{b:function(){ob()}},{b:function(){pb()}},{b:function(){qb()}},{b:function(){rb()}},
{b:function(){sb()}},{b:function(){tb()}},{b:function(){ub()}},{b:function(){vb()}},{b:function(){xb()}},{b:function(){yb()}},{b:function(){zb()}},{b:function(){Ab()}},{b:function(){Bb()}},{b:function(){Cb()}},{b:function(){Db()}},{b:function(){Eb()}},{b:function(){Fb()}},{b:function(){Gb()}},{b:function(){Hb()}},{b:function(){Ib()}},{b:function(){Jb()}},{b:function(){Kb()}},{b:function(){Lb()}},{b:function(){Mb()}},{b:function(){Nb()}},{b:function(){Ob()}},{b:function(){Pb()}},{b:function(){Qb()}},
{b:function(){Rb()}},{b:function(){Sb()}},{b:function(){Tb()}},{b:function(){Ub()}},{b:function(){Vb()}},{b:function(){Wb()}},{b:function(){Xb()}},{b:function(){Yb()}},{b:function(){Zb()}},{b:function(){$b()}},{b:function(){ac()}},{b:function(){bc()}},{b:function(){cc()}},{b:function(){dc()}},{b:function(){ec()}},{b:function(){fc()}},{b:function(){hc()}},{b:function(){ic()}},{b:function(){jc()}},{b:function(){kc()}},{b:function(){lc()}},{b:function(){mc()}},{b:function(){nc()}},{b:function(){oc()}},
{b:function(){pc()}},{b:function(){qc()}},{b:function(){rc()}},{b:function(){sc()}},{b:function(){tc()}},{b:function(){uc()}},{b:function(){vc()}},{b:function(){wc()}},{b:function(){xc()}},{b:function(){yc()}},{b:function(){zc()}},{b:function(){Ac()}},{b:function(){Bc()}},{b:function(){Cc()}},{b:function(){Dc()}},{b:function(){Ec()}},{b:function(){Fc()}},{b:function(){Gc()}},{b:function(){Hc()}},{b:function(){Ic()}});d.STATIC_BASE=Ca;d.STATIC_BUMP=1307520;w+=16;var I={};
function Jc(a){if(Jc.j){var b=F[a>>2];var c=F[b>>2]}else Jc.j=!0,I.USER=I.LOGNAME="web_user",I.PATH="/",I.PWD="/",I.HOME="/home/web_user",I.LANG="C.UTF-8",I._=d.thisProgram,c=sa(1024),b=sa(256),F[b>>2]=c,F[a>>2]=b;a=[];var e=0,f;for(f in I)if("string"===typeof I[f]){var g=f+"="+I[f];a.push(g);e+=g.length}if(1024<e)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){e=g=a[f];for(var h=c,l=0;l<e.length;++l)C[h++>>0]=e.charCodeAt(l);C[h>>0]=0;F[b+4*f>>2]=c;c+=g.length+1}F[b+
4*a.length>>2]=0}var Kc=0,Lc=[],J={};function Mc(a){if(!a||J[a])return a;for(var b in J){var c=+b;if(J[c].ra===a)return c}return a}function ___cxa_free_exception(a){try{return Nc(a)}catch(b){}}
function Oc(){var a=Kc;if(!a)return(Pc(0),0)|0;var b=J[a],c=b.type;if(!c)return(Pc(0),a)|0;var e=Array.prototype.slice.call(arguments);d.___cxa_is_pointer_type(c);Qc||(Qc=E(4));F[Qc>>2]=a;a=Qc;for(var f=0;f<e.length;f++)if(e[f]&&d.___cxa_can_catch(e[f],c,a))return a=F[a>>2],b.ra=a,(Pc(e[f]),a)|0;a=F[a>>2];return(Pc(c),a)|0}
var Qc,L={I:1,C:2,Rc:3,Nb:4,G:5,qa:6,gb:7,lc:8,B:9,ub:10,ma:11,ad:11,Ka:12,$:13,Gb:14,xc:15,aa:16,na:17,bd:18,da:19,oa:20,N:21,i:22,fc:23,Ja:24,H:25,Yc:26,Hb:27,tc:28,S:29,Oc:30,Zb:31,Hc:32,Db:33,Lc:34,pc:42,Kb:43,vb:44,Qb:45,Rb:46,Sb:47,Yb:48,Zc:49,jc:50,Pb:51,Ab:35,mc:37,mb:52,pb:53,cd:54,hc:55,qb:56,rb:57,Bb:35,sb:59,vc:60,kc:61,Vc:62,uc:63,qc:64,rc:65,Nc:66,nc:67,jb:68,Sc:69,wb:70,Ic:71,ac:72,Eb:73,ob:74,Cc:76,nb:77,Mc:78,Tb:79,Ub:80,Xb:81,Wb:82,Vb:83,wc:38,pa:39,bc:36,ba:40,Dc:95,Gc:96,zb:104,
ic:105,kb:97,Kc:91,Ac:88,sc:92,Pc:108,yb:111,hb:98,xb:103,ec:101,cc:100,Wc:110,Ib:112,Jb:113,Mb:115,lb:114,Cb:89,$b:90,Jc:93,Qc:94,ib:99,dc:102,Ob:106,yc:107,Xc:109,$c:87,Fb:122,Tc:116,Bc:95,oc:123,Lb:84,Ec:75,tb:125,zc:131,Fc:130,Uc:86};function Rc(a){d.___errno_location&&(F[d.___errno_location()>>2]=a);return a}
var Sc={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",
24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",
44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",
65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",
82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",
100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",
122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function Tc(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Uc(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Tc(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Vc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Wc(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Xc(){var a=Array.prototype.slice.call(arguments,0);return Uc(a.join("/"))}function M(a,b){return Uc(a+"/"+b)}
function Yc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Tc(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Zc=[];function $c(a,b){Zc[a]={input:[],output:[],M:b};ad(a,bd)}
var bd={open:function(a){var b=Zc[a.node.rdev];if(!b)throw new N(L.da);a.tty=b;a.seekable=!1},close:function(a){a.tty.M.flush(a.tty)},flush:function(a){a.tty.M.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.M.Da)throw new N(L.qa);for(var f=0,g=0;g<e;g++){try{var h=a.tty.M.Da(a.tty)}catch(l){throw new N(L.G);}if(void 0===h&&0===f)throw new N(L.ma);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.M.ka)throw new N(L.qa);
for(var f=0;f<e;f++)try{a.tty.M.ka(a.tty,b[c+f])}catch(g){throw new N(L.G);}e&&(a.node.timestamp=Date.now());return f}},dd={Da:function(a){if(!a.input.length){var b=null;if(p){var c=new Buffer(256),e=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{e=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))e=0;else throw h;}g&&fs.closeSync(f);0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=cd(b,!0)}return a.input.shift()},ka:function(a,b){null===b||10===b?(ha(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(xa(a.output,0)),a.output=[])}},ed={ka:function(a,b){null===b||10===b?(v(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(v(xa(a.output,0)),a.output=[])}},O={u:null,o:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,e){if(24576===(c&61440)||4096===(c&61440))throw new N(L.I);O.u||(O.u={dir:{node:{A:O.f.A,m:O.f.m,lookup:O.f.lookup,O:O.f.O,rename:O.f.rename,unlink:O.f.unlink,rmdir:O.f.rmdir,readdir:O.f.readdir,symlink:O.f.symlink},stream:{D:O.g.D}},file:{node:{A:O.f.A,m:O.f.m},stream:{D:O.g.D,read:O.g.read,write:O.g.write,sa:O.g.sa,Ga:O.g.Ga,V:O.g.V}},link:{node:{A:O.f.A,m:O.f.m,
readlink:O.f.readlink},stream:{}},wa:{node:{A:O.f.A,m:O.f.m},stream:fd}});c=gd(a,b,c,e);P(c.mode)?(c.f=O.u.dir.node,c.g=O.u.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=O.u.file.node,c.g=O.u.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=O.u.link.node,c.g=O.u.link.stream):8192===(c.mode&61440)&&(c.f=O.u.wa.node,c.g=O.u.wa.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},Ra:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},ed:function(a){return a.c?
a.c.subarray?a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},za:function(a,b){a.c&&a.c.subarray&&b>a.c.length&&(a.c=O.Ra(a),a.h=a.c.length);if(!a.c||a.c.subarray){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))}else for(!a.c&&0<b&&(a.c=[]);a.c.length<b;)a.c.push(0)},Xa:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));
c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{A:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.J=4096;b.blocks=Math.ceil(b.size/b.J);return b},
m:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Xa(a,b.size)},lookup:function(){throw hd[L.C];},O:function(a,b,c,e){return O.createNode(a,b,c,e)},rename:function(a,b,c){if(P(a.mode)){try{var e=id(b,c)}catch(g){}if(e)for(var f in e.c)throw new N(L.pa);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=id(a,b),e;for(e in c.c)throw new N(L.pa);delete a.c[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new N(L.i);return a.link}},g:{read:function(a,b,c,e,f){var g=a.node.c;if(f>=a.node.h)return 0;a=Math.min(a.node.h-f,e);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+e),a.h=e;if(0===a.h&&0===f)return a.c=new Uint8Array(b.subarray(c,c+e)),a.h=e;if(f+e<=a.h)return a.c.set(b.subarray(c,c+e),f),e}O.za(a,f+e);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.c[f+g]=b[c+g];a.h=Math.max(a.h,f+e);return e},D:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new N(L.i);return b},sa:function(a,b,c){O.za(a.node,b+c);a.node.h=Math.max(a.node.h,
b+c)},Ga:function(a,b,c,e,f,g,h){if(32768!==(a.node.mode&61440))throw new N(L.da);c=a.node.c;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+e<a.node.h)c.subarray?c=c.subarray(f,f+e):c=Array.prototype.slice.call(c,f,f+e);a=!0;e=E(e);if(!e)throw new N(L.Ka);b.set(c,e)}else a=!1,e=c.byteOffset;return{Wa:e,Na:a}},V:function(a,b,c,e,f){if(32768!==(a.node.mode&61440))throw new N(L.da);if(f&2)return 0;O.g.write(a,b,0,e,c,!1);return 0}}},Q={U:!1,$a:function(){Q.U=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);Q.Aa={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ta:function(a){return Buffer.j?Buffer.from(a):new Buffer(a)},o:function(a){assert(p);return Q.createNode(null,"/",Q.Ca(a.ja.root),0)},createNode:function(a,b,c){if(!P(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new N(L.i);a=gd(a,b,c);a.f=Q.f;a.g=Q.g;return a},Ca:function(a){try{var b=fs.lstatSync(a);Q.U&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new N(L[c.code]);}return b.mode},s:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.o.ja.root);b.reverse();return Xc.apply(null,b)},Qa:function(a){a&=-2656257;var b=0,c;for(c in Q.Aa)a&c&&(b|=Q.Aa[c],a^=c);if(a)throw new N(L.i);return b},f:{A:function(a){a=Q.s(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new N(L[c.code]);}Q.U&&!b.J&&(b.J=4096);Q.U&&!b.blocks&&(b.blocks=(b.size+b.J-1)/b.J|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,J:b.J,blocks:b.blocks}},m:function(a,b){var c=Q.s(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(e){if(!e.code)throw e;throw new N(L[e.code]);}},lookup:function(a,b){var c=M(Q.s(a),b);c=Q.Ca(c);return Q.createNode(a,b,c)},O:function(a,b,c,e){a=Q.createNode(a,b,c,e);b=Q.s(a);try{P(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new N(L[f.code]);}return a},rename:function(a,b,c){a=Q.s(a);b=M(Q.s(b),c);try{fs.renameSync(a,b)}catch(e){if(!e.code)throw e;throw new N(L[e.code]);}},unlink:function(a,b){a=M(Q.s(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new N(L[c.code]);}},rmdir:function(a,b){a=M(Q.s(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new N(L[c.code]);}},readdir:function(a){a=Q.s(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new N(L[b.code]);}},symlink:function(a,
b,c){a=M(Q.s(a),b);try{fs.symlinkSync(c,a)}catch(e){if(!e.code)throw e;throw new N(L[e.code]);}},readlink:function(a){var b=Q.s(a);try{return b=fs.readlinkSync(b),b=jd.relative(jd.resolve(a.o.ja.root),b)}catch(c){if(!c.code)throw c;throw new N(L[c.code]);}}},g:{open:function(a){var b=Q.s(a.node);try{32768===(a.node.mode&61440)&&(a.R=fs.openSync(b,Q.Qa(a.flags)))}catch(c){if(!c.code)throw c;throw new N(L[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.R&&fs.closeSync(a.R)}catch(b){if(!b.code)throw b;
throw new N(L[b.code]);}},read:function(a,b,c,e,f){if(0===e)return 0;try{return fs.readSync(a.R,Q.ta(b.buffer),c,e,f)}catch(g){throw new N(L[g.code]);}},write:function(a,b,c,e,f){try{return fs.writeSync(a.R,Q.ta(b.buffer),c,e,f)}catch(g){throw new N(L[g.code]);}},D:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.R).size}catch(e){throw new N(L[e.code]);}if(0>b)throw new N(L.i);return b}}};w+=16;w+=16;w+=16;
var kd=null,ld={},R=[],md=1,S=null,nd=!0,T={},N=null,hd={};
function U(a,b){a=Yc("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ba:!0,la:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.la)throw new N(L.ba);a=Tc(a.split("/").filter(function(a){return!!a}),!1);var f=kd;c="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=id(f,a[e]);c=M(c,a[e]);f.P&&(!g||g&&b.Ba)&&(f=f.P.root);if(!g||b.ga)for(g=0;40960===(f.mode&61440);)if(f=od(c),c=Yc(Vc(c),f),f=U(c,{la:b.la}).node,40<g++)throw new N(L.ba);}return{path:c,node:f}}
function V(a){for(var b;;){if(a===a.parent)return a=a.o.Ha,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function pd(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%S.length}function qd(a){var b=pd(a.parent.id,a.name);a.L=S[b];S[b]=a}function id(a,b){var c;if(c=(c=rd(a,"x"))?c:a.f.lookup?0:L.$)throw new N(c,a);for(c=S[pd(a.id,b)];c;c=c.L){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return a.f.lookup(a,b)}
function gd(a,b,c,e){sd||(sd=function(a,b,c,e){a||(a=this);this.parent=a;this.o=a.o;this.P=null;this.id=md++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=e},sd.prototype={},Object.defineProperties(sd.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ua:{get:function(){return P(this.mode)}},Ta:{get:function(){return 8192===(this.mode&
61440)}}}));a=new sd(a,b,c,e);qd(a);return a}function P(a){return 16384===(a&61440)}var td={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function ud(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function rd(a,b){if(nd)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return L.$}else return L.$;return 0}
function vd(a,b){try{return id(a,b),L.na}catch(c){}return rd(a,"wx")}function wd(a){var b=4096;for(a=a||0;a<=b;a++)if(!R[a])return a;throw new N(L.Ja);}function xd(a,b){yd||(yd=function(){},yd.prototype={},Object.defineProperties(yd.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new yd,e;for(e in a)c[e]=a[e];a=c;b=wd(b);a.fd=b;return R[b]=a}var fd={open:function(a){a.g=ld[a.node.rdev].g;a.g.open&&a.g.open(a)},D:function(){throw new N(L.S);}};
function ad(a,b){ld[a]={g:b}}function zd(a,b){var c="/"===b,e=!b;if(c&&kd)throw new N(L.aa);if(!c&&!e){var f=U(b,{Ba:!1});b=f.path;f=f.node;if(f.P)throw new N(L.aa);if(!P(f.mode))throw new N(L.oa);}b={type:a,ja:{},Ha:b,Va:[]};a=a.o(b);a.o=b;b.root=a;c?kd=a:f&&(f.P=b,f.o&&f.o.Va.push(b))}function Ad(a,b,c){var e=U(a,{parent:!0}).node;a=Wc(a);if(!a||"."===a||".."===a)throw new N(L.i);var f=vd(e,a);if(f)throw new N(f);if(!e.f.O)throw new N(L.I);return e.f.O(e,a,b,c)}
function W(a,b){return Ad(a,(void 0!==b?b:511)&1023|16384,0)}function Bd(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Ad(a,b|8192,c)}function Cd(a,b){if(!Yc(a))throw new N(L.C);var c=U(b,{parent:!0}).node;if(!c)throw new N(L.C);b=Wc(b);var e=vd(c,b);if(e)throw new N(e);if(!c.f.symlink)throw new N(L.I);return c.f.symlink(c,b,a)}
function Dd(a){var b=U(a,{parent:!0}).node,c=Wc(a),e=id(b,c);a:{try{var f=id(b,c)}catch(h){f=h.v;break a}var g=rd(b,"wx");f=g?g:P(f.mode)?L.N:0}if(f)throw new N(f);if(!b.f.unlink)throw new N(L.I);if(e.P)throw new N(L.aa);try{T.willDeletePath&&T.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.f.unlink(b,c);b=pd(e.parent.id,e.name);if(S[b]===e)S[b]=e.L;else for(b=S[b];b;){if(b.L===e){b.L=e.L;break}b=b.L}try{if(T.onDeletePath)T.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function od(a){a=U(a).node;if(!a)throw new N(L.C);if(!a.f.readlink)throw new N(L.i);return Yc(V(a.parent),a.f.readlink(a))}function Ed(a,b){var c;"string"===typeof a?c=U(a,{ga:!0}).node:c=a;if(!c.f.m)throw new N(L.I);c.f.m(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Fd(a,b,c,e){if(""===a)throw new N(L.C);if("string"===typeof b){var f=td[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Uc(a);try{g=U(a,{ga:!(b&131072)}).node}catch(n){}}f=!1;if(b&64)if(g){if(b&128)throw new N(L.na);}else g=Ad(a,c,0),f=!0;if(!g)throw new N(L.C);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!P(g.mode))throw new N(L.oa);if(!f){var h=g?40960===(g.mode&61440)?L.ba:
P(g.mode)&&("r"!==ud(b)||b&512)?L.N:rd(g,ud(b)):L.C;if(h)throw new N(h);}if(b&512){c=g;var l;"string"===typeof c?l=U(c,{ga:!0}).node:l=c;if(!l.f.m)throw new N(L.I);if(P(l.mode))throw new N(L.N);if(32768!==(l.mode&61440))throw new N(L.i);if(c=rd(l,"w"))throw new N(c);l.f.m(l,{size:0,timestamp:Date.now()})}b&=-641;e=xd({node:g,path:V(g),flags:b,seekable:!0,position:0,g:g.g,fb:[],error:!1},e);e.g.open&&e.g.open(e);!d.logReadFiles||b&1||(Gd||(Gd={}),a in Gd||(Gd[a]=1,h("read file: "+a)));try{T.onOpenFile&&
(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),T.onOpenFile(a,h))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return e}function Hd(a){if(null===a.fd)throw new N(L.B);a.ha&&(a.ha=null);try{a.g.close&&a.g.close(a)}catch(b){throw b;}finally{R[a.fd]=null}a.fd=null}function Id(a,b,c){if(null===a.fd)throw new N(L.B);if(!a.seekable||!a.g.D)throw new N(L.S);a.position=a.g.D(a,b,c);a.fb=[]}
function Jd(a,b,c,e,f,g){if(0>e||0>f)throw new N(L.i);if(null===a.fd)throw new N(L.B);if(0===(a.flags&2097155))throw new N(L.B);if(P(a.node.mode))throw new N(L.N);if(!a.g.write)throw new N(L.i);a.flags&1024&&Id(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new N(L.S);b=a.g.write(a,b,c,e,f,g);h||(a.position+=b);try{if(a.path&&T.onWriteToFile)T.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+l.message)}return b}
function Kd(){N||(N=function(a,b){this.node=b;this.Za=function(a){this.v=a;for(var b in L)if(L[b]===a){this.code=b;break}};this.Za(a);this.message=Sc[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},N.prototype=Error(),N.prototype.constructor=N,[L.C].forEach(function(a){hd[a]=new N(a);hd[a].stack="<generic error, no stack>"}))}var Ld;function Md(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Nd(a,b,c,e){a=M("string"===typeof a?a:V(a),b);return W(a,Md(c,e))}function Od(a,b){a="string"===typeof a?a:V(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=M(a,c);try{W(e)}catch(f){}a=e}}return e}function Pd(a,b,c,e){a=M("string"===typeof a?a:V(a),b);c=Md(c,e);return Ad(a,(void 0!==c?c:438)&4095|32768,0)}
function Qd(a,b,c,e,f,g){a=b?M("string"===typeof a?a:V(a),b):a;e=Md(e,f);f=Ad(a,(void 0!==e?e:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Ed(f,e|146);a=Fd(f,"w");Jd(a,c,0,c.length,0,g);Hd(a);Ed(f,e)}return f}
function X(a,b,c,e){a=M("string"===typeof a?a:V(a),b);b=Md(!!c,!!e);X.Fa||(X.Fa=64);var f=X.Fa++<<8|0;ad(f,{open:function(a){a.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(a,b,e,f){for(var g=0,h=0;h<f;h++){try{var l=c()}catch(B){throw new N(L.G);}if(void 0===l&&0===g)throw new N(L.ma);if(null===l||void 0===l)break;g++;b[e+h]=l}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{e(b[c+g])}catch(t){throw new N(L.G);}f&&(a.node.timestamp=
Date.now());return g}});return Bd(a,b,f)}function Rd(a,b,c){a=M("string"===typeof a?a:V(a),b);return Cd(c,a)}
function Sd(a){if(a.Ta||a.Ua||a.link||a.c)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(d.read)try{a.c=cd(d.read(a.url),!0),a.h=a.c.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||Rc(L.G);return b}
function Td(a,b,c,e,f){function g(){this.ia=!1;this.T=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Ea(a/this.chunkSize|0)[b]}};g.prototype.Ya=function(a){this.Ea=a};g.prototype.ua=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),e,f=(e=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
e;a=(e=a.getResponseHeader("Content-Encoding"))&&"gzip"===e;var g=1048576;f||(g=b);var h=this;h.Ya(function(a){var e=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.T[a]){var z=h.T;if(e>f)throw Error("invalid range ("+e+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var l=new XMLHttpRequest;l.open("GET",c,!1);b!==g&&l.setRequestHeader("Range","bytes="+e+"-"+f);"undefined"!=typeof Uint8Array&&(l.responseType="arraybuffer");l.overrideMimeType&&
l.overrideMimeType("text/plain; charset=x-user-defined");l.send(null);if(!(200<=l.status&&300>l.status||304===l.status))throw Error("Couldn't load "+c+". Status: "+l.status);e=void 0!==l.response?new Uint8Array(l.response||[]):cd(l.responseText||"",!0);z[a]=e}if("undefined"===typeof h.T[a])throw Error("doXHR failed!");return h.T[a]});if(a||!b)g=b=1,g=b=this.Ea(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ma=b;this.La=g;this.ia=!0};if("undefined"!==
typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.ia||this.ua();return this.Ma}},chunkSize:{get:function(){this.ia||this.ua();return this.La}}});var l=void 0}else l=c,h=void 0;var n=Pd(a,b,e,f);h?n.c=h:l&&(n.c=null,n.url=l);Object.defineProperties(n,{h:{get:function(){return this.c.length}}});var r={};Object.keys(n.g).forEach(function(a){var b=
n.g[a];r[a]=function(){if(!Sd(n))throw new N(L.G);return b.apply(null,arguments)}});r.read=function(a,b,c,e,f){if(!Sd(n))throw new N(L.G);a=a.node.c;if(f>=a.length)return 0;e=Math.min(a.length-f,e);assert(0<=e);if(a.slice)for(var g=0;g<e;g++)b[c+g]=a[f+g];else for(g=0;g<e;g++)b[c+g]=a.get(f+g);return e};n.g=r;return n}
function Ud(a,b,c,e,f,g,h,l,n,r){function t(c){function z(c){r&&r();l||Qd(a,b,c,e,f,n);g&&g();Ta()}var K=!1;d.preloadPlugins.forEach(function(a){!K&&a.canHandle(A)&&(a.handle(c,A,z,function(){h&&h();Ta()}),K=!0)});K||z(c)}Browser.gd();var A=b?Yc(M(a,b)):a;Sa();"string"==typeof c?Browser.dd(c,function(a){t(a)},h):t(c)}var FS={},sd,yd,Gd,Vd={},Y=0;function Z(){Y+=4;return F[Y-4>>2]}function Wd(){var a=R[Z()];if(!a)throw new N(L.B);return a}
function Xd(){void 0===Xd.start&&(Xd.start=Date.now());return 1E3*(Date.now()-Xd.start)|0}function Yd(a){if(0===a)return 0;a=H(a);if(!I.hasOwnProperty(a))return 0;Yd.j&&Nc(Yd.j);a=I[a];var b=za(a)+1,c=E(b);c&&oa(a,C,c,b);Yd.j=c;return Yd.j}function Zd(a){return Math.pow(2,a)}function $d(){$d.j||($d.j=[]);$d.j.push(x());return $d.j.length-1}
function ae(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!be){be=!0;F[ce()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);F[de()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var e=a(b),f=a(c);e=ra(cd(e));f=ra(cd(f));c.getTimezoneOffset()<b.getTimezoneOffset()?(F[ee()>>2]=e,F[ee()+4>>2]=f):(F[ee()>>2]=f,F[ee()+4>>2]=e)}}var be,fe={},ge=1;function he(a,b){he.j||(he.j={});a in he.j||(d.dynCall_v(b),he.j[a]=1)}
function ie(a){return 0===a%4&&(0!==a%100||0===a%400)}function je(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var ke=[31,29,31,30,31,30,31,31,30,31,30,31],le=[31,28,31,30,31,30,31,31,30,31,30,31];function ne(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(ie(a.getFullYear())?ke:le)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function oe(a,b,c,e){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var e;0===(e=c(a.getFullYear()-b.getFullYear()))&&0===(e=c(a.getMonth()-b.getMonth()))&&(e=c(a.getDate()-b.getDate()));return e}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function n(a){a=ne(new Date(a.l+1900,0,1),a.Z);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=F[e+40>>2];e={cb:F[e>>2],bb:F[e+4>>2],Y:F[e+8>>2],K:F[e+12>>2],F:F[e+16>>2],l:F[e+20>>2],Ia:F[e+24>>2],Z:F[e+28>>2],kd:F[e+32>>2],ab:F[e+36>>2],eb:r?H(r):
""};c=H(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var t in r)c=c.replace(new RegExp(t,"g"),r[t]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),B="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return A[a.Ia].substring(0,3)},"%A":function(a){return A[a.Ia]},"%b":function(a){return B[a.F].substring(0,
3)},"%B":function(a){return B[a.F]},"%C":function(a){return g((a.l+1900)/100|0,2)},"%d":function(a){return g(a.K,2)},"%e":function(a){return f(a.K,2," ")},"%g":function(a){return n(a).toString().substring(2)},"%G":function(a){return n(a)},"%H":function(a){return g(a.Y,2)},"%I":function(a){a=a.Y;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.K+je(ie(a.l+1900)?ke:le,a.F-1),3)},"%m":function(a){return g(a.F+1,2)},"%M":function(a){return g(a.bb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.Y&&12>a.Y?"AM":"PM"},"%S":function(a){return g(a.cb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.l+1900,a.F+1,a.K,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.l+1900,0,1),c=0===b.getDay()?b:ne(b,7-b.getDay());a=new Date(a.l+1900,a.F,a.K);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(je(ie(a.getFullYear())?ke:le,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.l+1900,0,4)),c=l(new Date(a.l+1901,0,4)),e=ne(new Date(a.l+
1900,0,1),a.Z);return 0>h(e,b)?"53":0>=h(c,e)?"01":g(Math.ceil((b.getFullYear()<a.l+1900?a.Z+32-b.getDate():a.Z+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.l+1900,a.F+1,a.K,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.l,0,1),c=1===b.getDay()?b:ne(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.l+1900,a.F,a.K);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(je(ie(a.getFullYear())?ke:le,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.l+1900).toString().substring(2)},
"%Y":function(a){return a.l+1900},"%z":function(a){a=a.ab;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.eb},"%%":function(){return"%"}};for(t in r)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),r[t](e)));t=cd(c,!1);if(t.length>b)return 0;C.set(t,a);return t.length-1}Kd();S=Array(4096);zd(O,"/");W("/tmp");W("/home");W("/home/web_user");
(function(){W("/dev");ad(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Bd("/dev/null",259);$c(1280,dd);$c(1536,ed);Bd("/dev/tty",1280);Bd("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else p?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){u("random_device")};X("/dev","random",b);X("/dev","urandom",b);W("/dev/shm");W("/dev/shm/tmp")})();W("/proc");W("/proc/self");W("/proc/self/fd");
zd({o:function(){var a=gd("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=R[+c];if(!b)throw new N(L.B);a={parent:null,o:{Ha:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ka.unshift(function(){if(!d.noFSInit&&!Ld){assert(!Ld,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Ld=!0;Kd();d.stdin=d.stdin;d.stdout=d.stdout;d.stderr=d.stderr;d.stdin?X("/dev","stdin",d.stdin):Cd("/dev/tty","/dev/stdin");d.stdout?X("/dev","stdout",null,d.stdout):Cd("/dev/tty","/dev/stdout");d.stderr?X("/dev","stderr",null,d.stderr):Cd("/dev/tty1","/dev/stderr");var a=
Fd("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Fd("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Fd("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});La.push(function(){nd=!1});Ma.push(function(){Ld=!1;var a=d._fflush;a&&a(0);for(a=0;a<R.length;a++){var b=R[a];b&&Hd(b)}});d.FS_createFolder=Nd;d.FS_createPath=Od;d.FS_createDataFile=Qd;d.FS_createPreloadedFile=Ud;d.FS_createLazyFile=Td;d.FS_createLink=Rd;
d.FS_createDevice=X;d.FS_unlink=Dd;Ka.unshift(function(){});Ma.push(function(){});if(p){var fs=require("fs"),jd=require("path");Q.$a()}va=ia(4);Da=Ea=ja(w);Fa=Da+Ha;Ga=ja(Fa);F[va>>2]=Ga;ta=!0;function cd(a,b){var c=Array(za(a)+1);a=oa(a,c,0,c.length);b&&(c.length=a);return c}d.wasmTableSize=11246;d.wasmMaxTableSize=11246;d.Oa={};
d.Pa={abort:u,enlargeMemory:function(){wa()},getTotalMemory:function(){return G},abortOnCannotGrowMemory:wa,invoke_i:function(a){var b=x();try{return d.dynCall_i(a)}catch(c){y(b);if("number"!==typeof c&&"longjmp"!==c)throw c;d.setThrew(1,0)}},invoke_ii:function(a,b){var c=x();try{return d.dynCall_ii(a,b)}catch(e){y(c);if("number"!==typeof e&&"longjmp"!==e)throw e;d.setThrew(1,0)}},invoke_iii:function(a,b,c){var e=x();try{return d.dynCall_iii(a,b,c)}catch(f){y(e);if("number"!==typeof f&&"longjmp"!==
f)throw f;d.setThrew(1,0)}},invoke_iiii:function(a,b,c,e){var f=x();try{return d.dynCall_iiii(a,b,c,e)}catch(g){y(f);if("number"!==typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},invoke_iiiii:function(a,b,c,e,f){var g=x();try{return d.dynCall_iiiii(a,b,c,e,f)}catch(h){y(g);if("number"!==typeof h&&"longjmp"!==h)throw h;d.setThrew(1,0)}},invoke_iiiiii:function(a,b,c,e,f,g){var h=x();try{return d.dynCall_iiiiii(a,b,c,e,f,g)}catch(l){y(h);if("number"!==typeof l&&"longjmp"!==l)throw l;d.setThrew(1,0)}},
invoke_iiiiiii:function(a,b,c,e,f,g,h){var l=x();try{return d.dynCall_iiiiiii(a,b,c,e,f,g,h)}catch(n){y(l);if("number"!==typeof n&&"longjmp"!==n)throw n;d.setThrew(1,0)}},invoke_iiiiiiii:function(a,b,c,e,f,g,h,l){var n=x();try{return d.dynCall_iiiiiiii(a,b,c,e,f,g,h,l)}catch(r){y(n);if("number"!==typeof r&&"longjmp"!==r)throw r;d.setThrew(1,0)}},invoke_iiiiiiiii:function(a,b,c,e,f,g,h,l,n){var r=x();try{return d.dynCall_iiiiiiiii(a,b,c,e,f,g,h,l,n)}catch(t){y(r);if("number"!==typeof t&&"longjmp"!==
t)throw t;d.setThrew(1,0)}},invoke_iiiiiiiiiiii:function(a,b,c,e,f,g,h,l,n,r,t,A){var B=x();try{return d.dynCall_iiiiiiiiiiii(a,b,c,e,f,g,h,l,n,r,t,A)}catch(z){y(B);if("number"!==typeof z&&"longjmp"!==z)throw z;d.setThrew(1,0)}},invoke_iiiiij:function(a,b,c,e,f,g,h){var l=x();try{return d.dynCall_iiiiij(a,b,c,e,f,g,h)}catch(n){y(l);if("number"!==typeof n&&"longjmp"!==n)throw n;d.setThrew(1,0)}},invoke_v:function(a){var b=x();try{d.dynCall_v(a)}catch(c){y(b);if("number"!==typeof c&&"longjmp"!==c)throw c;
d.setThrew(1,0)}},invoke_vi:function(a,b){var c=x();try{d.dynCall_vi(a,b)}catch(e){y(c);if("number"!==typeof e&&"longjmp"!==e)throw e;d.setThrew(1,0)}},invoke_vii:function(a,b,c){var e=x();try{d.dynCall_vii(a,b,c)}catch(f){y(e);if("number"!==typeof f&&"longjmp"!==f)throw f;d.setThrew(1,0)}},invoke_viii:function(a,b,c,e){var f=x();try{d.dynCall_viii(a,b,c,e)}catch(g){y(f);if("number"!==typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},invoke_viiii:function(a,b,c,e,f){var g=x();try{d.dynCall_viiii(a,
b,c,e,f)}catch(h){y(g);if("number"!==typeof h&&"longjmp"!==h)throw h;d.setThrew(1,0)}},invoke_viiiii:function(a,b,c,e,f,g){var h=x();try{d.dynCall_viiiii(a,b,c,e,f,g)}catch(l){y(h);if("number"!==typeof l&&"longjmp"!==l)throw l;d.setThrew(1,0)}},invoke_viiiiiii:function(a,b,c,e,f,g,h,l){var n=x();try{d.dynCall_viiiiiii(a,b,c,e,f,g,h,l)}catch(r){y(n);if("number"!==typeof r&&"longjmp"!==r)throw r;d.setThrew(1,0)}},invoke_viiiiiiii:function(a,b,c,e,f,g,h,l,n){var r=x();try{d.dynCall_viiiiiiii(a,b,c,e,
f,g,h,l,n)}catch(t){y(r);if("number"!==typeof t&&"longjmp"!==t)throw t;d.setThrew(1,0)}},invoke_viiiiiiiiii:function(a,b,c,e,f,g,h,l,n,r,t){var A=x();try{d.dynCall_viiiiiiiiii(a,b,c,e,f,g,h,l,n,r,t)}catch(B){y(A);if("number"!==typeof B&&"longjmp"!==B)throw B;d.setThrew(1,0)}},invoke_viiiiiiiiiiiiiii:function(a,b,c,e,f,g,h,l,n,r,t,A,B,z,K,na){var me=x();try{d.dynCall_viiiiiiiiiiiiiii(a,b,c,e,f,g,h,l,n,r,t,A,B,z,K,na)}catch(wb){y(me);if("number"!==typeof wb&&"longjmp"!==wb)throw wb;d.setThrew(1,0)}},
invoke_viij:function(a,b,c,e,f){var g=x();try{d.dynCall_viij(a,b,c,e,f)}catch(h){y(g);if("number"!==typeof h&&"longjmp"!==h)throw h;d.setThrew(1,0)}},invoke_viijii:function(a,b,c,e,f,g,h){var l=x();try{d.dynCall_viijii(a,b,c,e,f,g,h)}catch(n){y(l);if("number"!==typeof n&&"longjmp"!==n)throw n;d.setThrew(1,0)}},invoke_vij:function(a,b,c,e){var f=x();try{d.dynCall_vij(a,b,c,e)}catch(g){y(f);if("number"!==typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},invoke_viji:function(a,b,c,e,f){var g=x();try{d.dynCall_viji(a,
b,c,e,f)}catch(h){y(g);if("number"!==typeof h&&"longjmp"!==h)throw h;d.setThrew(1,0)}},invoke_vijii:function(a,b,c,e,f,g){var h=x();try{d.dynCall_vijii(a,b,c,e,f,g)}catch(l){y(h);if("number"!==typeof l&&"longjmp"!==l)throw l;d.setThrew(1,0)}},___assert_fail:function(a,b,c,e){u("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,e?H(e):"unknown function"])},___buildEnvironment:Jc,___cxa_allocate_exception:function(a){return E(a)},___cxa_begin_catch:function(a){var b=J[a];b&&!b.va&&(b.va=
!0,pe.fa--);b&&(b.X=!1);Lc.push(a);(b=Mc(a))&&J[b].W++;return a},___cxa_end_catch:function(){d.setThrew(0);var a=Lc.pop();if(a){if(a=Mc(a)){var b=J[a];assert(0<b.W);b.W--;0!==b.W||b.X||(b.ya&&d.dynCall_vi(b.ya,a),delete J[a],___cxa_free_exception(a))}Kc=0}},___cxa_find_matching_catch_2:function(){return Oc.apply(null,arguments)},___cxa_find_matching_catch_3:function(){return Oc.apply(null,arguments)},___cxa_find_matching_catch_4:function(){return Oc.apply(null,arguments)},___cxa_free_exception:___cxa_free_exception,
___cxa_pure_virtual:function(){la=!0;throw"Pure virtual function called!";},___cxa_rethrow:function(){var a=Lc.pop();a=Mc(a);J[a].X||(Lc.push(a),J[a].X=!0);Kc=a;throw a;},___cxa_throw:function(a,b,c){J[a]={Wa:a,ra:a,type:b,ya:c,W:0,va:!1,X:!1};Kc=a;"uncaught_exception"in pe?pe.fa++:pe.fa=1;throw a;},___cxa_uncaught_exception:function(){return!!pe.fa},___lock:function(){},___map_file:function(){Rc(L.I);return-1},___resumeException:function(a){Kc||(Kc=a);throw a;},___setErrNo:Rc,___syscall140:function(a,
b){Y=b;try{var c=Wd();Z();var e=Z(),f=Z(),g=Z();Id(c,e,g);F[f>>2]=c.position;c.ha&&0===e&&0===g&&(c.ha=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof N||u(h),-h.v}},___syscall145:function(a,b){Y=b;try{var c=Wd(),e=Z();a:{var f=Z();for(b=a=0;b<f;b++){var g=F[e+(8*b+4)>>2],h=c,l=F[e+8*b>>2],n=g,r=void 0,t=C;if(0>n||0>r)throw new N(L.i);if(null===h.fd)throw new N(L.B);if(1===(h.flags&2097155))throw new N(L.B);if(P(h.node.mode))throw new N(L.N);if(!h.g.read)throw new N(L.i);var A=
"undefined"!==typeof r;if(!A)r=h.position;else if(!h.seekable)throw new N(L.S);var B=h.g.read(h,t,l,n,r);A||(h.position+=B);var z=B;if(0>z){var K=-1;break a}a+=z;if(z<g)break}K=a}return K}catch(na){return"undefined"!==typeof FS&&na instanceof N||u(na),-na.v}},___syscall146:function(a,b){Y=b;try{var c=Wd(),e=Z();a:{var f=Z();for(b=a=0;b<f;b++){var g=Jd(c,C,F[e+8*b>>2],F[e+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(l){return"undefined"!==typeof FS&&l instanceof N||u(l),-l.v}},
___syscall221:function(a,b){Y=b;try{var c=Wd();switch(Z()){case 0:var e=Z();return 0>e?-L.i:Fd(c.path,c.flags,0,e).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return e=Z(),c.flags|=e,0;case 12:case 12:return e=Z(),Aa[e+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-L.i;case 9:return Rc(L.i),-1;default:return-L.i}}catch(f){return"undefined"!==typeof FS&&f instanceof N||u(f),-f.v}},___syscall5:function(a,b){Y=b;try{var c=H(Z()),e=Z(),f=Z();return Fd(c,e,f).fd}catch(g){return"undefined"!==
typeof FS&&g instanceof N||u(g),-g.v}},___syscall54:function(a,b){Y=b;try{var c=Wd(),e=Z();switch(e){case 21509:case 21505:return c.tty?0:-L.H;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-L.H;case 21519:if(!c.tty)return-L.H;var f=Z();return F[f>>2]=0;case 21520:return c.tty?-L.i:-L.H;case 21531:a=f=Z();if(!c.g.Sa)throw new N(L.H);return c.g.Sa(c,e,a);case 21523:return c.tty?0:-L.H;case 21524:return c.tty?0:-L.H;default:u("bad ioctl syscall "+e)}}catch(g){return"undefined"!==
typeof FS&&g instanceof N||u(g),-g.v}},___syscall6:function(a,b){Y=b;try{var c=Wd();Hd(c);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof N||u(e),-e.v}},___syscall91:function(a,b){Y=b;try{var c=Z(),e=Z(),f=Vd[c];if(!f)return 0;if(e===f.hd){var g=R[f.fd],h=f.flags,l=new Uint8Array(D.subarray(c,c+e));g&&g.g.V&&g.g.V(g,l,0,e,h);Vd[c]=null;f.Na&&Nc(f.jd)}return 0}catch(n){return"undefined"!==typeof FS&&n instanceof N||u(n),-n.v}},___unlock:function(){},_abort:function(){d.abort()},_clock:Xd,
_emscripten_memcpy_big:function(a,b,c){D.set(D.subarray(b,b+c),a);return a},_getenv:Yd,_llvm_eh_typeid_for:function(a){return a},_llvm_exp2_f64:function(){return Zd.apply(null,arguments)},_llvm_stackrestore:function(a){var b=$d.j[a];$d.j.splice(a,1);y(b)},_llvm_stacksave:$d,_llvm_trap:function(){u("trap!")},_mktime:function(a){ae();var b=new Date(F[a+20>>2]+1900,F[a+16>>2],F[a+12>>2],F[a+8>>2],F[a+4>>2],F[a>>2],0),c=F[a+32>>2],e=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(2E3,
6,1)).getTimezoneOffset(),h=f.getTimezoneOffset(),l=Math.min(h,g);0>c?F[a+32>>2]=Number(g!=h&&l==e):0<c!=(l==e)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?l:g)-e)));F[a+24>>2]=b.getDay();F[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},_pthread_cond_wait:function(){return 0},_pthread_getspecific:function(a){return fe[a]||0},_pthread_key_create:function(a){if(0==a)return L.i;F[a>>2]=ge;fe[ge]=0;ge++;return 0},_pthread_once:he,_pthread_setspecific:function(a,b){if(!(a in
fe))return L.i;fe[a]=b;return 0},_strftime_l:function(a,b,c,e){return oe(a,b,c,e)},_sysconf:function(a){switch(a){case 30:return 16384;case 85:return D.length/16384;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}Rc(L.i);return-1},
DYNAMICTOP_PTR:va,STACKTOP:Ea};var qe=d.asm(d.Oa,d.Pa,buffer);d.asm=qe;
var Va=d.__GLOBAL__I_000101=function(){return d.asm.__GLOBAL__I_000101.apply(null,arguments)},Fc=d.__GLOBAL__sub_I_Adapter_cpp=function(){return d.asm.__GLOBAL__sub_I_Adapter_cpp.apply(null,arguments)},Ec=d.__GLOBAL__sub_I_Spectre_cpp=function(){return d.asm.__GLOBAL__sub_I_Spectre_cpp.apply(null,arguments)},Dc=d.__GLOBAL__sub_I_archive_supp_common_cpp=function(){return d.asm.__GLOBAL__sub_I_archive_supp_common_cpp.apply(null,arguments)},fc=d.__GLOBAL__sub_I_ascscreencrusher_cpp=function(){return d.asm.__GLOBAL__sub_I_ascscreencrusher_cpp.apply(null,
arguments)},mb=d.__GLOBAL__sub_I_ascsoundmaster_cpp=function(){return d.asm.__GLOBAL__sub_I_ascsoundmaster_cpp.apply(null,arguments)},zc=d.__GLOBAL__sub_I_ay_supp_cpp=function(){return d.asm.__GLOBAL__sub_I_ay_supp_cpp.apply(null,arguments)},oc=d.__GLOBAL__sub_I_aym_cpp=function(){return d.asm.__GLOBAL__sub_I_aym_cpp.apply(null,arguments)},pc=d.__GLOBAL__sub_I_aym_cpp_144=function(){return d.asm.__GLOBAL__sub_I_aym_cpp_144.apply(null,arguments)},cc=d.__GLOBAL__sub_I_charpres_cpp=function(){return d.asm.__GLOBAL__sub_I_charpres_cpp.apply(null,
arguments)},vb=d.__GLOBAL__sub_I_chiptracker_cpp=function(){return d.asm.__GLOBAL__sub_I_chiptracker_cpp.apply(null,arguments)},bc=d.__GLOBAL__sub_I_codecruncher3_cpp=function(){return d.asm.__GLOBAL__sub_I_codecruncher3_cpp.apply(null,arguments)},ac=d.__GLOBAL__sub_I_compiledasc_cpp=function(){return d.asm.__GLOBAL__sub_I_compiledasc_cpp.apply(null,arguments)},$b=d.__GLOBAL__sub_I_compiledpt2_cpp=function(){return d.asm.__GLOBAL__sub_I_compiledpt2_cpp.apply(null,arguments)},Zb=d.__GLOBAL__sub_I_compiledptu13_cpp=
function(){return d.asm.__GLOBAL__sub_I_compiledptu13_cpp.apply(null,arguments)},Yb=d.__GLOBAL__sub_I_compiledst3_cpp=function(){return d.asm.__GLOBAL__sub_I_compiledst3_cpp.apply(null,arguments)},Xb=d.__GLOBAL__sub_I_compiledstp_cpp=function(){return d.asm.__GLOBAL__sub_I_compiledstp_cpp.apply(null,arguments)},Wb=d.__GLOBAL__sub_I_compressorcode4_cpp=function(){return d.asm.__GLOBAL__sub_I_compressorcode4_cpp.apply(null,arguments)},Vb=d.__GLOBAL__sub_I_datasquieezer_cpp=function(){return d.asm.__GLOBAL__sub_I_datasquieezer_cpp.apply(null,
arguments)},ub=d.__GLOBAL__sub_I_digitalmusicmaker_cpp=function(){return d.asm.__GLOBAL__sub_I_digitalmusicmaker_cpp.apply(null,arguments)},tb=d.__GLOBAL__sub_I_digitalstudio_cpp=function(){return d.asm.__GLOBAL__sub_I_digitalstudio_cpp.apply(null,arguments)},uc=d.__GLOBAL__sub_I_enumerator_cpp=function(){return d.asm.__GLOBAL__sub_I_enumerator_cpp.apply(null,arguments)},Ub=d.__GLOBAL__sub_I_esvcruncher_cpp=function(){return d.asm.__GLOBAL__sub_I_esvcruncher_cpp.apply(null,arguments)},Ab=d.__GLOBAL__sub_I_etracker_cpp=
function(){return d.asm.__GLOBAL__sub_I_etracker_cpp.apply(null,arguments)},sb=d.__GLOBAL__sub_I_extremetracker1_cpp=function(){return d.asm.__GLOBAL__sub_I_extremetracker1_cpp.apply(null,arguments)},lb=d.__GLOBAL__sub_I_fasttracker_cpp=function(){return d.asm.__GLOBAL__sub_I_fasttracker_cpp.apply(null,arguments)},Ac=d.__GLOBAL__sub_I_freq_tables_cpp=function(){return d.asm.__GLOBAL__sub_I_freq_tables_cpp.apply(null,arguments)},Tb=d.__GLOBAL__sub_I_fulldiskimage_cpp=function(){return d.asm.__GLOBAL__sub_I_fulldiskimage_cpp.apply(null,
arguments)},Sb=d.__GLOBAL__sub_I_gamepacker_cpp=function(){return d.asm.__GLOBAL__sub_I_gamepacker_cpp.apply(null,arguments)},Za=d.__GLOBAL__sub_I_globaltracker_cpp=function(){return d.asm.__GLOBAL__sub_I_globaltracker_cpp.apply(null,arguments)},Hc=d.__GLOBAL__sub_I_grammar_cpp=function(){return d.asm.__GLOBAL__sub_I_grammar_cpp.apply(null,arguments)},Rb=d.__GLOBAL__sub_I_hobeta_cpp=function(){return d.asm.__GLOBAL__sub_I_hobeta_cpp.apply(null,arguments)},hc=d.__GLOBAL__sub_I_hrip_cpp=function(){return d.asm.__GLOBAL__sub_I_hrip_cpp.apply(null,
arguments)},Qb=d.__GLOBAL__sub_I_hrum_cpp=function(){return d.asm.__GLOBAL__sub_I_hrum_cpp.apply(null,arguments)},Pb=d.__GLOBAL__sub_I_hrust1_cpp=function(){return d.asm.__GLOBAL__sub_I_hrust1_cpp.apply(null,arguments)},Ob=d.__GLOBAL__sub_I_hrust2_cpp=function(){return d.asm.__GLOBAL__sub_I_hrust2_cpp.apply(null,arguments)},Ic=d.__GLOBAL__sub_I_iostream_cpp=function(){return d.asm.__GLOBAL__sub_I_iostream_cpp.apply(null,arguments)},ec=d.__GLOBAL__sub_I_lasercompact40_cpp=function(){return d.asm.__GLOBAL__sub_I_lasercompact40_cpp.apply(null,
arguments)},dc=d.__GLOBAL__sub_I_lasercompact52_cpp=function(){return d.asm.__GLOBAL__sub_I_lasercompact52_cpp.apply(null,arguments)},mc=d.__GLOBAL__sub_I_lha_cpp=function(){return d.asm.__GLOBAL__sub_I_lha_cpp.apply(null,arguments)},Nb=d.__GLOBAL__sub_I_lzh_cpp=function(){return d.asm.__GLOBAL__sub_I_lzh_cpp.apply(null,arguments)},Mb=d.__GLOBAL__sub_I_lzs_cpp=function(){return d.asm.__GLOBAL__sub_I_lzs_cpp.apply(null,arguments)},Lb=d.__GLOBAL__sub_I_megalz_cpp=function(){return d.asm.__GLOBAL__sub_I_megalz_cpp.apply(null,
arguments)},sc=d.__GLOBAL__sub_I_module_detect_cpp=function(){return d.asm.__GLOBAL__sub_I_module_detect_cpp.apply(null,arguments)},xc=d.__GLOBAL__sub_I_module_properties_cpp=function(){return d.asm.__GLOBAL__sub_I_module_properties_cpp.apply(null,arguments)},Kb=d.__GLOBAL__sub_I_mspack_cpp=function(){return d.asm.__GLOBAL__sub_I_mspack_cpp.apply(null,arguments)},ic=d.__GLOBAL__sub_I_multiay_cpp=function(){return d.asm.__GLOBAL__sub_I_multiay_cpp.apply(null,arguments)},Jb=d.__GLOBAL__sub_I_pack2_cpp=
function(){return d.asm.__GLOBAL__sub_I_pack2_cpp.apply(null,arguments)},Xa=d.__GLOBAL__sub_I_parameters_cpp=function(){return d.asm.__GLOBAL__sub_I_parameters_cpp.apply(null,arguments)},Cc=d.__GLOBAL__sub_I_parameters_cpp_1306=function(){return d.asm.__GLOBAL__sub_I_parameters_cpp_1306.apply(null,arguments)},tc=d.__GLOBAL__sub_I_parameters_cpp_145=function(){return d.asm.__GLOBAL__sub_I_parameters_cpp_145.apply(null,arguments)},qc=d.__GLOBAL__sub_I_path_cpp=function(){return d.asm.__GLOBAL__sub_I_path_cpp.apply(null,
arguments)},yc=d.__GLOBAL__sub_I_plugin_cpp=function(){return d.asm.__GLOBAL__sub_I_plugin_cpp.apply(null,arguments)},Ib=d.__GLOBAL__sub_I_powerfullcodedecreaser6_cpp=function(){return d.asm.__GLOBAL__sub_I_powerfullcodedecreaser6_cpp.apply(null,arguments)},rb=d.__GLOBAL__sub_I_prodigitracker_cpp=function(){return d.asm.__GLOBAL__sub_I_prodigitracker_cpp.apply(null,arguments)},kb=d.__GLOBAL__sub_I_prosoundcreator_cpp=function(){return d.asm.__GLOBAL__sub_I_prosoundcreator_cpp.apply(null,arguments)},
jb=d.__GLOBAL__sub_I_prosoundmaker_compiled_cpp=function(){return d.asm.__GLOBAL__sub_I_prosoundmaker_compiled_cpp.apply(null,arguments)},ib=d.__GLOBAL__sub_I_protracker1_cpp=function(){return d.asm.__GLOBAL__sub_I_protracker1_cpp.apply(null,arguments)},hb=d.__GLOBAL__sub_I_protracker2_cpp=function(){return d.asm.__GLOBAL__sub_I_protracker2_cpp.apply(null,arguments)},gb=d.__GLOBAL__sub_I_protracker3_compiled_cpp=function(){return d.asm.__GLOBAL__sub_I_protracker3_compiled_cpp.apply(null,arguments)},
fb=d.__GLOBAL__sub_I_protracker3_vortex_cpp=function(){return d.asm.__GLOBAL__sub_I_protracker3_vortex_cpp.apply(null,arguments)},eb=d.__GLOBAL__sub_I_psg_cpp=function(){return d.asm.__GLOBAL__sub_I_psg_cpp.apply(null,arguments)},vc=d.__GLOBAL__sub_I_raw_supp_cpp=function(){return d.asm.__GLOBAL__sub_I_raw_supp_cpp.apply(null,arguments)},qb=d.__GLOBAL__sub_I_sampletracker_cpp=function(){return d.asm.__GLOBAL__sub_I_sampletracker_cpp.apply(null,arguments)},jc=d.__GLOBAL__sub_I_scl_cpp=function(){return d.asm.__GLOBAL__sub_I_scl_cpp.apply(null,
arguments)},Hb=d.__GLOBAL__sub_I_sna128_cpp=function(){return d.asm.__GLOBAL__sub_I_sna128_cpp.apply(null,arguments)},db=d.__GLOBAL__sub_I_soundtracker3_cpp=function(){return d.asm.__GLOBAL__sub_I_soundtracker3_cpp.apply(null,arguments)},bb=d.__GLOBAL__sub_I_soundtracker_compiled_cpp=function(){return d.asm.__GLOBAL__sub_I_soundtracker_compiled_cpp.apply(null,arguments)},cb=d.__GLOBAL__sub_I_soundtracker_cpp=function(){return d.asm.__GLOBAL__sub_I_soundtracker_cpp.apply(null,arguments)},ab=d.__GLOBAL__sub_I_soundtrackerpro_compiled_cpp=
function(){return d.asm.__GLOBAL__sub_I_soundtrackerpro_compiled_cpp.apply(null,arguments)},pb=d.__GLOBAL__sub_I_sqdigitaltracker_cpp=function(){return d.asm.__GLOBAL__sub_I_sqdigitaltracker_cpp.apply(null,arguments)},ob=d.__GLOBAL__sub_I_sqtracker_compiled_cpp=function(){return d.asm.__GLOBAL__sub_I_sqtracker_compiled_cpp.apply(null,arguments)},Wa=d.__GLOBAL__sub_I_syntax_cpp=function(){return d.asm.__GLOBAL__sub_I_syntax_cpp.apply(null,arguments)},Gb=d.__GLOBAL__sub_I_teledisk_cpp=function(){return d.asm.__GLOBAL__sub_I_teledisk_cpp.apply(null,
arguments)},xb=d.__GLOBAL__sub_I_tfc_cpp=function(){return d.asm.__GLOBAL__sub_I_tfc_cpp.apply(null,arguments)},yb=d.__GLOBAL__sub_I_tfd_cpp=function(){return d.asm.__GLOBAL__sub_I_tfd_cpp.apply(null,arguments)},zb=d.__GLOBAL__sub_I_tfmmusicmaker_cpp=function(){return d.asm.__GLOBAL__sub_I_tfmmusicmaker_cpp.apply(null,arguments)},kc=d.__GLOBAL__sub_I_trd_cpp=function(){return d.asm.__GLOBAL__sub_I_trd_cpp.apply(null,arguments)},Fb=d.__GLOBAL__sub_I_trush_cpp=function(){return d.asm.__GLOBAL__sub_I_trush_cpp.apply(null,
arguments)},rc=d.__GLOBAL__sub_I_ts_base_cpp=function(){return d.asm.__GLOBAL__sub_I_ts_base_cpp.apply(null,arguments)},Eb=d.__GLOBAL__sub_I_turbolz_cpp=function(){return d.asm.__GLOBAL__sub_I_turbolz_cpp.apply(null,arguments)},nb=d.__GLOBAL__sub_I_turbosound_cpp=function(){return d.asm.__GLOBAL__sub_I_turbosound_cpp.apply(null,arguments)},nc=d.__GLOBAL__sub_I_turbosound_cpp_110=function(){return d.asm.__GLOBAL__sub_I_turbosound_cpp_110.apply(null,arguments)},Bc=d.__GLOBAL__sub_I_vtx_supp_cpp=function(){return d.asm.__GLOBAL__sub_I_vtx_supp_cpp.apply(null,
arguments)},$a=d.__GLOBAL__sub_I_ym_vtx_cpp=function(){return d.asm.__GLOBAL__sub_I_ym_vtx_cpp.apply(null,arguments)},Db=d.__GLOBAL__sub_I_z80_cpp=function(){return d.asm.__GLOBAL__sub_I_z80_cpp.apply(null,arguments)},wc=d.__GLOBAL__sub_I_zdata_supp_cpp=function(){return d.asm.__GLOBAL__sub_I_zdata_supp_cpp.apply(null,arguments)},Cb=d.__GLOBAL__sub_I_zip_file_cpp=function(){return d.asm.__GLOBAL__sub_I_zip_file_cpp.apply(null,arguments)},lc=d.__GLOBAL__sub_I_zxstate_cpp=function(){return d.asm.__GLOBAL__sub_I_zxstate_cpp.apply(null,
arguments)},Bb=d.__GLOBAL__sub_I_zxzip_file_cpp=function(){return d.asm.__GLOBAL__sub_I_zxzip_file_cpp.apply(null,arguments)},pe=d.__ZSt18uncaught_exceptionv=function(){return d.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)};d.___cxa_can_catch=function(){return d.asm.___cxa_can_catch.apply(null,arguments)};d.___cxa_is_pointer_type=function(){return d.asm.___cxa_is_pointer_type.apply(null,arguments)};
var Ya=d.___cxx_global_var_init_16=function(){return d.asm.___cxx_global_var_init_16.apply(null,arguments)},Gc=d.___emscripten_environ_constructor=function(){return d.asm.___emscripten_environ_constructor.apply(null,arguments)};d.___errno_location=function(){return d.asm.___errno_location.apply(null,arguments)};
var de=d.__get_daylight=function(){return d.asm.__get_daylight.apply(null,arguments)},ce=d.__get_timezone=function(){return d.asm.__get_timezone.apply(null,arguments)},ee=d.__get_tzname=function(){return d.asm.__get_tzname.apply(null,arguments)};d._emu_compute_audio_samples=function(){return d.asm._emu_compute_audio_samples.apply(null,arguments)};d._emu_get_audio_buffer=function(){return d.asm._emu_get_audio_buffer.apply(null,arguments)};
d._emu_get_audio_buffer_length=function(){return d.asm._emu_get_audio_buffer_length.apply(null,arguments)};d._emu_get_current_position=function(){return d.asm._emu_get_current_position.apply(null,arguments)};d._emu_get_max_position=function(){return d.asm._emu_get_max_position.apply(null,arguments)};d._emu_get_sample_rate=function(){return d.asm._emu_get_sample_rate.apply(null,arguments)};d._emu_get_track_info=function(){return d.asm._emu_get_track_info.apply(null,arguments)};
d._emu_load_file=function(){return d.asm._emu_load_file.apply(null,arguments)};d._emu_seek_position=function(){return d.asm._emu_seek_position.apply(null,arguments)};d._emu_set_subsong=function(){return d.asm._emu_set_subsong.apply(null,arguments)};d._emu_teardown=function(){return d.asm._emu_teardown.apply(null,arguments)};
var Nc=d._free=function(){return d.asm._free.apply(null,arguments)},E=d._malloc=function(){return d.asm._malloc.apply(null,arguments)},Pc=d.setTempRet0=function(){return d.asm.setTempRet0.apply(null,arguments)};d.setThrew=function(){return d.asm.setThrew.apply(null,arguments)};var ma=d.stackAlloc=function(){return d.asm.stackAlloc.apply(null,arguments)},y=d.stackRestore=function(){return d.asm.stackRestore.apply(null,arguments)},x=d.stackSave=function(){return d.asm.stackSave.apply(null,arguments)};
d.dynCall_i=function(){return d.asm.dynCall_i.apply(null,arguments)};d.dynCall_ii=function(){return d.asm.dynCall_ii.apply(null,arguments)};d.dynCall_iii=function(){return d.asm.dynCall_iii.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};d.dynCall_iiiii=function(){return d.asm.dynCall_iiiii.apply(null,arguments)};d.dynCall_iiiiii=function(){return d.asm.dynCall_iiiiii.apply(null,arguments)};
d.dynCall_iiiiiii=function(){return d.asm.dynCall_iiiiiii.apply(null,arguments)};d.dynCall_iiiiiiii=function(){return d.asm.dynCall_iiiiiiii.apply(null,arguments)};d.dynCall_iiiiiiiii=function(){return d.asm.dynCall_iiiiiiiii.apply(null,arguments)};d.dynCall_iiiiiiiiiiii=function(){return d.asm.dynCall_iiiiiiiiiiii.apply(null,arguments)};d.dynCall_iiiiij=function(){return d.asm.dynCall_iiiiij.apply(null,arguments)};d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};
d.dynCall_vi=function(){return d.asm.dynCall_vi.apply(null,arguments)};d.dynCall_vii=function(){return d.asm.dynCall_vii.apply(null,arguments)};d.dynCall_viii=function(){return d.asm.dynCall_viii.apply(null,arguments)};d.dynCall_viiii=function(){return d.asm.dynCall_viiii.apply(null,arguments)};d.dynCall_viiiii=function(){return d.asm.dynCall_viiiii.apply(null,arguments)};d.dynCall_viiiiiii=function(){return d.asm.dynCall_viiiiiii.apply(null,arguments)};
d.dynCall_viiiiiiii=function(){return d.asm.dynCall_viiiiiiii.apply(null,arguments)};d.dynCall_viiiiiiiiii=function(){return d.asm.dynCall_viiiiiiiiii.apply(null,arguments)};d.dynCall_viiiiiiiiiiiiiii=function(){return d.asm.dynCall_viiiiiiiiiiiiiii.apply(null,arguments)};d.dynCall_viij=function(){return d.asm.dynCall_viij.apply(null,arguments)};d.dynCall_viijii=function(){return d.asm.dynCall_viijii.apply(null,arguments)};d.dynCall_vij=function(){return d.asm.dynCall_vij.apply(null,arguments)};
d.dynCall_viji=function(){return d.asm.dynCall_viji.apply(null,arguments)};d.dynCall_vijii=function(){return d.asm.dynCall_vijii.apply(null,arguments)};d.asm=qe;d.ccall=function(a,b,c,e){var f=d["_"+a];assert(f,"Cannot call unknown function "+a+", make sure it is exported");var g=[];a=0;if(e)for(var h=0;h<e.length;h++){var l=qa[c[h]];l?(0===a&&(a=x()),g[h]=l(e[h])):g[h]=e[h]}c=f.apply(null,g);c="string"===b?H(c):"boolean"===b?!!c:c;0!==a&&y(a);return c};d.getMemory=sa;d.Pointer_stringify=H;
d.addRunDependency=Sa;d.removeRunDependency=Ta;d.FS_createFolder=Nd;d.FS_createPath=Od;d.FS_createDataFile=Qd;d.FS_createPreloadedFile=Ud;d.FS_createLazyFile=Td;d.FS_createLink=Rd;d.FS_createDevice=X;d.FS_unlink=Dd;Ra=function re(){d.calledRun||se();d.calledRun||(Ra=re)};
function se(){function a(){if(!d.calledRun&&(d.calledRun=!0,!la)){ua||(ua=!0,Ia(Ka));Ia(La);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var a=d.postRun.shift();Na.unshift(a)}Ia(Na)}}if(!(0<Pa)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Oa();Ia(Ja);0<Pa||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);a()},1)):a())}}d.run=se;function u(a){if(d.onAbort)d.onAbort(a);void 0!==a?(ha(a),v(a),a=JSON.stringify(a)):a="";la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}d.abort=u;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();d.noExitRuntime=!0;se();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_ZXTUNE);
/*
 zxtune_adapter.js: Adapts ZxTune backend to generic WebAudio/ScriptProcessor player.

   version 1.1
   copyright (C) 2015-2023 Juergen Wothke

 LICENSE

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2.1 of the License, or (at
 your option) any later version. This library is distributed in the hope
 that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
*/
class ZxTuneBackendAdapter extends EmsHEAP16BackendAdapter {
	constructor()
	{
		super(backend_ZxTune.Module, 2, new SimpleFileMapper(backend_ZxTune.Module));

		this.ensureReadyNotification();
	}

	loadMusicData(sampleRate, path, filename, data, options)
	{
		filename = this._getFilename(path, filename);

		let ret = this.Module.ccall('emu_load_file', 'number',
							['string', 'number', 'number', 'number', 'number', 'number'],
							[ filename, 0, 0, ScriptNodePlayer.getWebAudioSampleRate(), 1024, false]);

		if (ret == 0)
		{
			this._setupOutputResampling(sampleRate);
		}
		return ret;
	}

	evalTrackOptions(options)
	{
		super.evalTrackOptions(options);

		let id = (options && options.track) ? options.track : 0;
		return this.Module.ccall('emu_set_subsong', 'number', ['number'], [id]);
	}

	getSongInfoMeta()
	{
		return {
			title: String,
			author: String,
			desc: String,
			program: String,
			subPath: String,
			tracks: Number,
			currentTrack: Number
		};
	}

	updateSongInfo(filename)
	{
		let result = this._songInfo;
		
		let numAttr = 7;
		let ret = this.Module.ccall('emu_get_track_info', 'number');

		let array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);
		result.title = this.Module.Pointer_stringify(array[0]);
		if (!result.title.length)
		{
			result.title = this._makeTitleFromPath(filename);
		}
		result.author = this.Module.Pointer_stringify(array[1]);
		result.desc = this.Module.Pointer_stringify(array[2]);
		result.program = this.Module.Pointer_stringify(array[3]);
		result.subPath = this.Module.Pointer_stringify(array[4]);

		let t = this.Module.Pointer_stringify(array[5]);
		result.tracks = parseInt(t);

		let ct = this.Module.Pointer_stringify(array[6]);
		result.currentTrack = parseInt(ct);
	}
};
