#ifndef LIBSIDPLAYFP_VERSION_H
#define LIBSIDPLAYFP_VERSION_H

#ifndef SIDPLAYFP_H
#  error Do not include directly.
#endif



#define LIBSIDPLAYFP_VERSION_MAJ 2
#define LIBSIDPLAYFP_VERSION_MIN 15
#define LIBSIDPLAYFP_VERSION_LEV 2

#endif
