////////////////////////////////////////////////////////////////////////////////
//
////////////////////////////////////////////////////////////////////////////////
//
//
//
//
//
//
//
////////////////////////////////////////////////////////////////////////////////

#ifndef __SEGMENTM_H__
#define __SEGMENTM_H__
#define	MB_COLOR	0x00FFFFFF
#define	MF_COLOR	0x00000000

DWORD sleepM[] = {
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR
};

DWORD verticalM[] = {
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR
};

DWORD horizontalM[] = {
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR
};

DWORD circle1M[] = {
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR
};
DWORD circle2M[] = {
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR
};
DWORD circle3M[] = {
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MF_COLOR,MF_COLOR,MF_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,
	MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR,MB_COLOR
};
#endif
