//
//  snes_spcSets.m
//  modizer
//
//  Created by Yohann Magnien David on 20/01/2026.
//
// Based on snesmusicv2 torrent data as of 2026/01/20
// 1520 entries

// RSN filename to full name mapping
// Auto-generated from rsnsets.dat

#include "ModizerTypes.h"

const rsn_name_mapping_t SNESmusic_names[] = {
    {"33ejh", "3x3 Eyes - Juuma Houkan"},
    {"33esk", "3x3 Eyes - Seima Kourinden"},
    {"3nkb", "3 Ninjas Kick Back"},
    {"4ns", "4 Nin Shogi"},
    {"7sg", "7th Saga"},
    {"a88", "U.N. Squadron"},
    {"aat", "Andre Agassi Tennis"},
    {"abd", "American Battle Dome"},
    {"abr", "Adventures of Batman and Robin, The"},
    {"acc", "Akazukin Cha Cha"},
    {"accb", "Accelebrid"},
    {"acd", "Christmas Demo"},
    {"ace", "Ace o Nerae!"},
    {"acme", "ACME Animation Factory"},
    {"acrm", "Acrobat Mission"},
    {"actp", "Action Pachio"},
    {"actr", "Actraiser"},
    {"actr2", "Actraiser 2"},
    {"adf", "Addams Family, The"},
    {"ads", "Aoki Densetsu Shoot!"},
    {"aero", "Aero the Acro-Bat"},
    {"aero2", "Aero the Acro-Bat 2"},
    {"afam2", "Addams Family, The - Pugsley's Scavenger Hunt"},
    {"afv", "Addams Family Values"},
    {"ag", "American Gladiators"},
    {"aging", "Aging Cassette"},
    {"agogo", "Uchuu Race Astro Go Go"},
    {"ahawk", "Astrohawk - May 2003 Version"},
    {"airc", "Air Cavalry"},
    {"airm", "Air Management - Ozora ni Kakeru (Aerobiz)"},
    {"airm2", "Air Management 2 - Koukuu Ou wo Mezase (Aerobiz Supersonic)"},
    {"al3", "Alien 3"},
    {"ala", "Aladdin"},
    {"alca", "Alcahest"},
    {"alch", "Alfred Chicken"},
    {"alft", "Ardy Lightfoot"},
    {"alice", "Alice's Paint Adventure"},
    {"alod", "Albert Odyssey"},
    {"alod2", "Albert Odyssey 2"},
    {"amdz", "Archer MacLean's Dropzone"},
    {"amnf", "ABC Monday Night Football"},
    {"an", "Arabian Nights"},
    {"ani", "Animaniacs"},
    {"anigb", "Animaniacs (Super Gameboy)"},
    {"apii", "Apocalypse II"},
    {"apmj", "Armor Police Metal Jack"},
    {"apple", "Appleseed - Prometheus no Shintaku"},
    {"aqua", "Super Aquatic Games (James Pond's Crazy Sports)"},
    {"ar", "Araiguma Rascal"},
    {"arbf", "Adventures of Rocky and Bullwinkle and Friends, The"},
    {"arc", "Arcus Spirits"},
    {"are", "Aretha"},
    {"are2", "Aretha 2"},
    {"ari3", "A Ressha de Ikou 3 Super Version"},
    {"arm", "AAAHH!!! Real Monsters"},
    {"aryol", "Aryol"},
    {"asf1", "Aguri Suzuki F-1 Super Driving"},
    {"asp", "A.S.P. Air Strike Patrol"},
    {"asr", "Asahi Shinbun Rensai"},
    {"ast", "Asterix"},
    {"ast2", "Asterix & Obelix"},
    {"astj", "Ashita no Joe"},
    {"atfgw", "An American Tail - Fievel Goes West"},
    {"aurt", "Al Unser Jr's Road to the Top"},
    {"avsp", "Alien vs. Predator"},
    {"axe", "Axelay"},
    {"ballz", "Ballz 3D"},
    {"basc", "Bass Master Classic"},
    {"bascp", "Bass Master Classic Pro Edition"},
    {"bast", "Bastard!!"},
    {"batb", "Beauty and the Beast"},
    {"bazb", "Bazooka Blitzkrieg"},
    {"bbb", "Bing Bing! Bingo"},
    {"bbd", "Bomberman B-Daman"},
    {"bbg", "Ball Bullet Gun"},
    {"bbh", "Beavis and Butt-Head"},
    {"bbk", "Bebe's Kids"},
    {"bbr", "Bugs Bunny - Rabbit Rampage"},
    {"bbs", "Bubsy in Claws Encounters of the Furred Kind"},
    {"bbs2", "Bubsy 2"},
    {"bbt", "Bouncing Ball Trainer"},
    {"bc", "Battle Clash"},
    {"bcar", "Battle Cars"},
    {"bcr", "Battle Cross"},
    {"bdash", "BS Bdash"},
    {"bdb2", "Battle Dodgeball 2"},
    {"bdh", "Brandish"},
    {"bdh2", "Brandish 2"},
    {"bdodg", "Battle Dodgeball"},
    {"bdz", "Bishin Densetsu Zoku"},
    {"bevb", "Beach Volleyball (Super Gameboy)"},
    {"bf", "Batman Forever"},
    {"bfn1", "Itoi Shigesato no Bass Tsuri No.1 (Shigesato Itoi's Bass Fishing No.1)"},
    {"bg", "Benkei Gaiden"},
    {"bhh", "Brett Hull Hockey"},
    {"bhh95", "Brett Hull Hockey '95"},
    {"bio", "Bio Metal"},
    {"biow", "Bioworm"},
    {"bj", "Battle Jockey"},
    {"bkdc", "Bakutou Dodgers"},
    {"bkz", "Block Kuzushi"},
    {"bl", "Bahamut Lagoon"},
    {"blcb", "Bill Laimbeer's Combat Basketball"},
    {"blues", "Blues Brothers, The"},
    {"blzn", "Blazeon"},
    {"bm", "Battle Master"},
    {"bmfm", "Biker Mice From Mars"},
    {"bmg", "Bokujou Monogatari (Harvest Moon)"},
    {"bms", "Bazoe! Mahou Sekai (Ancient Magic)"},
    {"bnkr", "Bonkers"},
    {"bnts", "Bounty Sword"},
    {"bob", "B.O.B."},
    {"bobby", "Bobby's World"},
    {"bof", "Breath of Fire"},
    {"bof2", "Breath of Fire 2"},
    {"bonk", "Super Bonk"},
    {"boog", "Boogerman"},
    {"botb", "Best of the Best - Championship Karate"},
    {"br", "Batman Returns"},
    {"brace", "Battle Racers"},
    {"brain", "Brainies"},
    {"brawl", "Brawl Brothers"},
    {"brbr", "Barbarossa"},
    {"breakt", "BreakThru!"},
    {"brj", "Batman - Revenge of the Joker"},
    {"brld", "Brain Lord"},
    {"brnr", "Brass Numbers"},
    {"bronk", "Bronkie"},
    {"brtl", "Brutal - Paws of Fury"},
    {"bsd", "Bram Stoker's Dracula"},
    {"bsdq", "BS Dragon Quest"},
    {"bsec", "Beethoven's 2nd"},
    {"bshs", "Bushi Seiryuden"},
    {"bsim", "Super Baseball Simulator 1.000"},
    {"bsj", "Barkley - Shut Up and Jam!"},
    {"bsm", "Barbie Super Model"},
    {"bsmr", "Bishoujo Senshi Sailormoon R"},
    {"bsnm", "BS Nichibutsu Mahjong"},
    {"bssm", "Bishoujo Senshi Sailormoon"},
    {"bssw2", "BS Saterawalker 2"},
    {"bst", "Big Sky Trooper"},
    {"bsub", "Battle Submarine"},
    {"bsx", "Satellaview BS-X"},
    {"bsz", "BS Zelda"},
    {"btbm", "Battletoads in Battlemania"},
    {"btbz", "Battle Blaze"},
    {"btdd", "Battletoads & Double Dragon"},
    {"btfh", "Battle Tycoon - Flash Hiders SFX"},
    {"btgp", "Battle Grand Prix"},
    {"btmb", "Gekitotsu Dangan Jidousha Kessen - Battle Mobile"},
    {"btpb", "Battle Pinball"},
    {"btrex", "Baby T-Rex"},
    {"btsc", "Battle Soccer - Field no Hasha"},
    {"btsc2", "Battle Soccer 2"},
    {"bug", "A Bug's Life (Super Gameboy)"},
    {"burai", "Burai - Hachigyoku no Yuushi Densetsu"},
    {"burn", "SNES Burn-in Test Cart"},
    {"bust", "BS Buster's Digital Magazine"},
    {"bva", "Barbie Vacation Adventure"},
    {"bvb", "Bulls vs. Blazers"},
    {"bwcf", "Bill Walsh College Football"},
    {"bwh", "Bishoujo Wrestlinger's History"},
    {"bwtc", "Brunswick World Tournament of Champions"},
    {"bzd", "Battle Zeque Den"},
    {"cace", "Carrier Aces"},
    {"cagj", "Cute Angela - Great Journey"},
    {"cakn", "Cacoma Knight"},
    {"cano", "Captain Novolin"},
    {"capam", "Captain America and the Avengers"},
    {"captc", "Captain Commando"},
    {"car", "Gekisou Sentai Car Rangers"},
    {"card", "Cardmaster (Arcana)"},
    {"cas", "Casper (Japanese Version)"},
    {"casp", "Casper (American Version)"},
    {"cb", "Crystal Beans - From Dungeon Explorer"},
    {"cb9", "Cyborg 009"},
    {"cbcw", "CB Chara Wars"},
    {"cbtr", "Combatribes"},
    {"cctcf", "Chester Cheetah - Too Cool to Fool"},
    {"ccup", "Cannondale Cup"},
    {"ccwwq", "Chester Cheetah Wild Wild Quest"},
    {"cd79", "Kidou Senshi Gundam - Cross Dimension 0079"},
    {"cf", "Cannon Fodder"},
    {"cfu97", "College Football USA '97"},
    {"cgp", "Cosmo Gang the Puzzle"},
    {"cgv", "Cosmo Gang the Video"},
    {"cheap", "BS Cheap de Gorgeous"},
    {"chinh", "Chinhai"},
    {"cho", "Chou Aniki - Bakuretsu Rantou Hen"},
    {"circ", "Kyle Petty's No Fear Racing (Circuit USA)"},
    {"civ", "Civilization"},
    {"ck", "Cyber Knight"},
    {"ck2", "Cyber Knight 2"},
    {"ckc", "Classic Kong Complete"},
    {"cl3", "Choplifter 3"},
    {"clay", "Clay Fighter"},
    {"cliff", "Cliffhanger"},
    {"clue", "Clue"},
    {"cmf", "Capcom's MVP Football"},
    {"cml", "Cameltry (On the Ball)"},
    {"cn", "Cybernator"},
    {"cngc", "Congo's Caper"},
    {"cnkub", "Computer Nouryoku Kaiseki Ultra Baken"},
    {"cntr3", "Contra 3"},
    {"col", "Columns"},
    {"colu", "BS Columbus no Tamagoyaki"},
    {"coolw", "Cool World"},
    {"cop", "Cu-On-Pa"},
    {"corl", "Coron Land"},
    {"cornb", "Corn Buster"},
    {"cp", "Championship Pool"},
    {"cpg2", "Cosmo Police Galivan 2"},
    {"crjb", "Cal Ripken Jr. Baseball"},
    {"crock", "Chuck Rock"},
    {"crs", "Crayon Shin-chan - Arashi wo yobu Enji"},
    {"crs2", "Crayon Shin-chan 2"},
    {"crsnd", "Crayon Shin-chan - Nagagutsu Dobon!!"},
    {"cs", "Chaos Seed"},
    {"csb", "College Slam Basketball"},
    {"csc", "Caravan Shooting Collection"},
    {"cspot", "Cool Spot"},
    {"csz", "Congo the Movie - The Secret of Zinj"},
    {"ct", "Chrono Trigger"},
    {"ct3", "Captain Tsubasa 3"},
    {"ct4", "Captain Tsubasa 4"},
    {"ct5", "Captain Tsubasa 5"},
    {"ctc", "Controller Test Cartridge"},
    {"cti", "Cutthroat Island"},
    {"ctj", "Captain Tsubasa J"},
    {"ctow", "Clock Tower"},
    {"ctp", "Chrono Trigger Pre-Release"},
    {"cttn", "Marchen Adventure Cotton 100%"},
    {"cw", "Clock Works"},
    {"cwcs", "Champions World Class Soccer"},
    {"daha", "Dark Half"},
    {"dala", "Dark Law - Meaning of Death"},
    {"dals", "Dolucky's A-League Soccer"},
    {"dance", "Tuff E Nuff"},
    {"dany", "Super Dany"},
    {"dark", "Dark Kingdom"},
    {"dars", "Death and Return of Superman, The"},
    {"dbc", "Daze Before Christmas"},
    {"dbhd", "Dragon Ball Z - Hyper Dimension"},
    {"dbls", "Dragon - The Bruce Lee Story"},
    {"dboys", "Dear Boys"},
    {"dbra", "Death Brade"},
    {"dbth", "Dragon Ball Z Super Gokuden - Totsugeki-Hen"},
    {"dbzb", "Dragon Ball Z - Super Butouden"},
    {"dbzb2", "Dragon Ball Z - Super Butouden 2"},
    {"dbzb3", "Dragon Ball Z - Super Butouden 3"},
    {"dbzr", "Dragon Ball Z RPG - Legend of the Super Saiya-jin"},
    {"dc", "Demon's Crest"},
    {"dcat", "David Crane's Amazing Tennis"},
    {"dd5", "Double Dragon 5"},
    {"ddmb", "Donald Duck - Mahou no Boushi"},
    {"dds", "Dino Dini's Soccer"},
    {"de", "Daisenryaku Expert"},
    {"de2", "Daisenryaku Expert WWII"},
    {"deman", "Demolition Man"},
    {"dezae", "Kaite Tukutte Asoberu Dezaemon"},
    {"df", "Darius Force (Super Nova)"},
    {"dgb", "Dossun! Ganseki Battle"},
    {"dhdo", "Dharma Doujou"},
    {"dici", "Dino City"},
    {"difo", "Dimension Force"},
    {"dirt", "Dirt Racer"},
    {"dirty", "Kinnikuman - Dirty Challenger"},
    {"dj", "Derby Jockey"},
    {"dj2", "Derby Jockey 2"},
    {"dk", "Donkey Kong (Super Gameboy)"},
    {"dk4", "Dragon Knight 4"},
    {"dkc", "Donkey Kong Country"},
    {"dkdt", "Donkey Kong Country 3"},
    {"dkm", "Dai Kaiju Monogatari"},
    {"dkq", "Donkey Kong Country 2"},
    {"dks2", "Doukyuusei 2"},
    {"dkvt", "Date Kimiko no Virtual Tennis"},
    {"dky", "Dolucky's Kusa Yakyu"},
    {"dl", "Der Langrisser"},
    {"dlp", "Demon of Laplace"},
    {"dlpt", "Dolucky no Puzzle Tour '94"},
    {"dm", "Dungeon Master"},
    {"dmkd", "Dream Maze - Kigurumi Daibouken"},
    {"dnbm", "Downtown Nekketsu Baseball Monogatari"},
    {"do", "Dual Orb"},
    {"do2", "Dual Orb 2"},
    {"doh", "Arkanoid - Doh it Again"},
    {"doka", "Dokapon 321"},
    {"doom", "Doom"},
    {"dor", "Doraemon"},
    {"dor2", "Doraemon 2"},
    {"dor3", "Doraemon 3"},
    {"dor4", "Doraemon 4"},
    {"dq12", "Dragon Quest 1 & 2"},
    {"dq3", "Dragon Quest 3"},
    {"dq5", "Dragon Quest 5"},
    {"dq6", "Dragon Quest 6"},
    {"dqai", "Dorque and Imp"},
    {"drea", "Dragon's Earth"},
    {"drf", "Adventures of Dr. Franken"},
    {"drk", "Drakkhen"},
    {"drla", "Dragon's Lair"},
    {"drm", "BS Do-Re-Mi"},
    {"drmf", "Do-Re-Mi Fantasy - Milon no DokiDoki Daibouken"},
    {"ds9", "Star Trek Deep Space Nine - The Crossroads of Time"},
    {"dslh", "Dragon Slayer - The Legend of Heroes"},
    {"dsrg", "Desert Strike - Return to the Gulf"},
    {"dt", "DynamiTracer"},
    {"dtai", "Deae Tonosama Appare Ichiban"},
    {"dtfx", "Dirt Trax FX"},
    {"dtlv", "Dynamaite - The LasVegas"},
    {"dtm", "Dennis the Menace"},
    {"dtr", "Doom Troopers"},
    {"dtv", "Dream TV"},
    {"dtw", "Down the World"},
    {"dtwin", "Darius Twin"},
    {"dunq", "Dun Quest"},
    {"dv", "Dragon View (Drakkhen 2)"},
    {"dvr", "Road Runner's Death Valley Rally"},
    {"dx", "Dracula X (Castlevania V - Vampire's Kiss)"},
    {"earl", "Earth Light"},
    {"eb", "Energy Breaker"},
    {"ebt", "ESPN Baseball Tonight"},
    {"ed", "Estpolis Denki (Lufia and the Fortress of Doom)"},
    {"ed2", "Lufia 2 - Rise of the Sinistrals"},
    {"edf", "Super E.D.F. - Earth Defense Force"},
    {"edk", "Edo no Kiba"},
    {"eh", "Exhaust Heat"},
    {"eh2", "Exhaust Heat 2"},
    {"ehn", "ESPN National Hockey Night"},
    {"eikt", "Sangokushi Eiketsu Den"},
    {"elf", "Elfaria"},
    {"elf2", "Elfaria 2"},
    {"emd", "Emerald Dragon"},
    {"enf", "Eien no Filena"},
    {"eotb", "Eye of the Beholder"},
    {"eq", "Equinox (Solstice II)"},
    {"esc", "Elite Soccer"},
    {"esf", "Emmitt Smith Football"},
    {"espns", "ESPN Sunday Night NFL"},
    {"esprk", "Esparks - Ijikuu kara no Raihousha"},
    {"espw", "ESPN Speedworld"},
    {"est2p", "Estpolis Denki 2 (Lufia 2) Prototype"},
    {"etc", "EEK! The Cat"},
    {"eurit", "Eurit"},
    {"evo", "E.V.O. - Search for Eden"},
    {"ewj", "Earthworm Jim"},
    {"ewj2", "Earthworm Jim 2"},
    {"f1gp", "F-1 Grand Prix"},
    {"f1gp2", "F-1 Grand Prix Part II"},
    {"f1gp3", "F-1 Grand Prix Part III"},
    {"f1wc", "F1 World Championship Edition"},
    {"f91", "Gundam F-91"},
    {"f97gb", "FIFA Soccer '97 (Super Gameboy)"},
    {"f98gb", "FIFA Soccer '98 (Super Gameboy)"},
    {"famd", "Family Dog"},
    {"fb", "Faceball 2000"},
    {"fdogs", "Ren & Stimpy Show - Fire Dogs"},
    {"fdp", "Fight da Pon!"},
    {"fe3", "Fire Emblem - Mystery of the Emblem"},
    {"fe4", "Fire Emblem - Genealogy of Holy-War"},
    {"feoez", "Tengai Makyo Zero (Far East of Eden Zero)"},
    {"fet", "Fire Emblem Thracia 776"},
    {"feud", "Family Feud"},
    {"ff4", "Final Fantasy 4"},
    {"ff5", "Final Fantasy V"},
    {"ff6", "Final Fantasy 6"},
    {"ffi", "Final Fight"},
    {"ffi2", "Final Fight 2"},
    {"ffi3", "Final Fight 3"},
    {"fflea", "Frantic Flea"},
    {"ffmq", "Final Fantasy USA - Mystic Quest"},
    {"ffr", "Foreman For Real"},
    {"ffu", "Fatal Fury"},
    {"ffu2", "Fatal Fury 2"},
    {"ffus", "Fatal Fury Special"},
    {"fgpx", "Future GPX - Cyber Formula"},
    {"fh", "Fighter's History"},
    {"fh2", "Fighter's History 2"},
    {"fhbd", "Flying Hero - Bugyuru no Daibouken"},
    {"fir", "Firemen, The"},
    {"firea", "Firearm"},
    {"flint", "Flintstones"},
    {"fls", "Flashback"},
    {"fm", "Front Mission"},
    {"fmw", "Onita Atsushi FMW"},
    {"fng", "Fun 'N Games"},
    {"footf", "Football Fury"},
    {"fpwx", "Super Fire Pro Wrestling X"},
    {"fq", "First Queen"},
    {"frgr", "Frogger"},
    {"frog", "FrogNES"},
    {"frsa", "First Samurai"},
    {"fs", "Farland Story"},
    {"fs2", "Farland Story 2"},
    {"fs96", "FIFA Soccer '96"},
    {"fs97", "FIFA 97 - Gold Edition"},
    {"fsr", "Fire Striker"},
    {"fst", "Finalset Tennis"},
    {"fstr", "Final Stretch"},
    {"ftb", "Masaki Shimono no Fishing To Bassing"},
    {"ftc2", "Famicom Tantei Club 2"},
    {"ftm", "Fireteam Rogue"},
    {"ftr", "Full Throttle Racing"},
    {"ftsd", "From TV Animation Slam Dunk"},
    {"ftsd2", "From TV Animation Slam Dunk 2"},
    {"ftsdh", "From TV Animation Slam Dunk - SD Heat Up!"},
    {"ftsm", "Flintstones - Treasure of Sierra Madrock"},
    {"furo", "BS Furoito no Chousenjou"},
    {"fz", "F-Zero"},
    {"gadg", "Inspector Gadget"},
    {"gage", "Game Genie"},
    {"gam", "Gamars Copier"},
    {"gambh", "Gamble Hourouki"},
    {"gb3", "Great Battle 3"},
    {"gb4", "Great Battle IV, The"},
    {"gb5", "Great Battle 5"},
    {"gbg2", "Great Battle Gaiden 2"},
    {"gboy", "Kuusou Kagaku Sekai Gulliver Boy"},
    {"gbt", "Gokinjo Bouken Tai"},
    {"gcd", "Ghost Chaser Densei"},
    {"gd3", "Gradius 3"},
    {"gdl", "GD Leen"},
    {"gdng", "Ganbare Daiku no Gensan"},
    {"ged", "Ginga Eiyuu Densetsu"},
    {"gek", "BS Gekkan Coin Toss Deck"},
    {"gen2", "Genocide 2"},
    {"genjr", "Genjuu Ryodan"},
    {"gfko", "George Foreman's KO Boxing"},
    {"gg", "Ganbare Goemon (Legend of the Mystical Ninja)"},
    {"gg2", "Ganbare Goemon 2 - Kiteretsu Shogun Magginesu!"},
    {"gg3", "Ganbare Goemon 3 - Shishi Juroku Hyoe no Karakuri Manji Katame!"},
    {"gg4", "Ganbare Goemon 4 - Kirakira Douchuu"},
    {"gga", "Go Go Ackman"},
    {"gga2", "Go Go Ackman 2"},
    {"gga3", "Go Go Ackman 3"},
    {"ggdl", "Go! Go! Dodge League"},
    {"ggg", "Gan Gan Ganchan"},
    {"gggs", "Gamera - Gyaosu Gekimetsu Sakusen"},
    {"gh", "Front Mission - Gun Hazard"},
    {"ghis", "Granhistoria"},
    {"ghoul", "Ghoul Patrol"},
    {"gion", "Gionbana"},
    {"gjc2", "Gambler Jiko Chuushinha 2 - Dorapon Quest"},
    {"gk2", "Super Aoki Ookami to Shiroki Mejika - Genchou Hishi (Genghis Khan 2 - Clan of the Grey Wolf)"},
    {"gkd", "Godzilla - Kaijuu Daikessen"},
    {"gkh", "Gakko de atta Kowai Hanashi"},
    {"gna", "Getsumen no Anubis"},
    {"gnk", "Gegege no Kitaro"},
    {"gnpl", "Gunple - Gunman's Proof"},
    {"god", "G.O.D. - Mezameyo to Yobu Koe ha Kikoe"},
    {"gods", "Gods"},
    {"gp", "Gokujyo Parodius (Parodius 2)"},
    {"gp1", "Gp-1"},
    {"gp1p2", "GP-1 Part II"},
    {"gpgg7", "BS Goods Press 7"},
    {"gpggs", "BS Goods Press 3"},
    {"gpo", "Ganso Pachinko Ou"},
    {"grobo", "Galaxy Robo"},
    {"gs", "Shinzui Taikyoku Igo Go Sennin"},
    {"gsby", "Gourmet Sentai Bara Yarou"},
    {"gsgr", "Ginga Sengoku Gunyuuden Rai"},
    {"gsm", "Ghost Sweeper Mikami - Gokuraku Daisakusen"},
    {"gt", "Goof Troop"},
    {"gtr", "GT Racing"},
    {"gunf", "Gun Force"},
    {"guts", "Nickelodeon GUTS"},
    {"gw", "Galaxy Wars"},
    {"gwed", "Gundam Wing - Endless Duel"},
    {"h7f", "Hisshou 777 Fighter"},
    {"h7f2", "Hisshou 777 Fighter II"},
    {"h7f3", "Hisshou 777 Fighter III"},
    {"ha", "Home Alone"},
    {"ha2", "Home Alone 2"},
    {"hag", "Hagane"},
    {"hahe", "Hanjuku Hero"},
    {"haji", "Hajimari no Mori (The Forest of Beginnings)"},
    {"hb", "Harapeko Bakka"},
    {"hb3", "Hardball 3"},
    {"hbtt", "Hanna Barbera's Turbo Toons"},
    {"hdn", "Hiouden - Mamono Tachi Tono Chikai"},
    {"he3", "Heracles no Eikou III"},
    {"he4", "Heracles no Eikou IV - Kamigami kara no Okurimono"},
    {"herc", "Hercules (Super Gameboy)"},
    {"hf", "Hanafuda"},
    {"hfo", "Hanafuda Ou"},
    {"hgb", "Hourai Gakuen no Bouken"},
    {"hgp", "Human Grand Prix"},
    {"hgp2", "Human Grand Prix 2"},
    {"hgp3", "Human Grand Prix 3"},
    {"hgp4", "Human Grand Prix 4"},
    {"hgs", "Heisei Gunjin Shougi"},
    {"hha", "Harley's Humongous Adventure"},
    {"hhu", "Heian Huunden"},
    {"higo", "Honkakuha Igo - Gosei"},
    {"himp", "Home Improvement"},
    {"hk5", "Hokuto no Ken 5"},
    {"hk6", "Hokuto no Ken 6"},
    {"hk7", "Hokuto no Ken 7"},
    {"hk97", "Hong Kong 97"},
    {"hkgf", "Hiryu no Ken S - Golden Fighter"},
    {"hmat", "Honkaku Mahjong Tetsuman"},
    {"hmos", "Habu Meijin no Omoshiro Shougi"},
    {"hmr", "Haisei Mahjong Ryouga"},
    {"hnd", "Hunchback of Notre Dame (Super Gameboy)"},
    {"hndd", "Honoo no Toukyuuji - Dodge Danpei"},
    {"hnms", "Hayazashi Nidan - Morita Shogi"},
    {"hnp", "Hebereke no Popun"},
    {"hook", "Hook"},
    {"hopi", "Hebereke no Oishii Puzzle wa Irimasekna"},
    {"hos", "Head-On Soccer"},
    {"hp93", "Hakunetsu Pro Yakyuu '93 - Ganba League"},
    {"hp94", "Hakunetsu Pro Yakyuu '94 - Ganba League 3"},
    {"hpgl", "Hakunetsu Pro Yakyuu - Ganba League"},
    {"hro", "Hunt for Red October"},
    {"hs", "Hero Senki"},
    {"hsfr", "Honkaku Shougi Fuuunji Ryuuou"},
    {"hsh", "Hashire Hebereke"},
    {"ht", "Hurricanes Trainer"},
    {"hth2", "Hat Trick Hero 2"},
    {"hti", "Hit the Ice"},
    {"hu", "Holy Umbrella"},
    {"hulk", "Incredible Hulk, The"},
    {"human", "Humans"},
    {"hurr", "Hurricanes"},
    {"hvbsv", "Hyper V-Ball (Super Volley II)"},
    {"hyir", "Hyper Iria"},
    {"hyst", "Hysteria"},
    {"hzkd", "Hansei Zarujirou Kun no Daibouken (Spanky's Quest)"},
    {"hzone", "Hyper Zone"},
    {"icom", "Iron Commando"},
    {"idea", "Idea no Hi"},
    {"igf", "Ignition Factor"},
    {"igoc", "Igo Club"},
    {"ihrsd", "Itou Hatasu Rokudan no Shougi Dojo"},
    {"ijga", "Indiana Jones' Greatest Adventures"},
    {"im", "Ihatovo Monogatari"},
    {"imp", "Imperium"},
    {"inca", "Incantation"},
    {"ini", "Inindo - Way of the Ninja (Super Inindo - Datou Nobunaga)"},
    {"ins", "Illvanian no Shiro"},
    {"iog", "Illusion of Gaia"},
    {"ipgt", "Ippatsu Gyakuten - Keiba Keirin Kyotei"},
    {"is2", "Itadaki Street 2"},
    {"isbv", "Inazuma Serve da!!"},
    {"isg", "Itchy and Scratchy Game"},
    {"iss", "International Superstar Soccer"},
    {"issdx", "International Superstar Soccer Deluxe"},
    {"itt", "International Tennis Tour"},
    {"izzy", "Izzy's Quest for the Olympic Rings"},
    {"jamit", "Jammit"},
    {"jbook", "Jungle Book, The"},
    {"jboy", "Jelly Boy"},
    {"jboy2", "Jelly Boy 2"},
    {"jbrr", "Jaleco Rally Big Run - The Supreme 4WD Challenge"},
    {"jc", "Jaki Crush"},
    {"jcptt", "Jimmy Connors Pro Tennis Tour"},
    {"jd", "Judge Dredd"},
    {"jeop", "Jeopardy!"},
    {"jerry", "Jerry Boy (Smartball)"},
    {"jets", "Jetsons - Invasion of the Planet Pirates"},
    {"jgk", "Janyuuki Gokuu Randa"},
    {"jkyo", "Jissen Kyotei"},
    {"jle94", "J League Excite Stage '94"},
    {"jle95", "J-League Excite Stage '95"},
    {"jlpg", "J-League Soccer Prime Goal"},
    {"jlpg2", "J-League Soccer Prime Goal 2"},
    {"jlpg3", "J-League Soccer Prime Goal 3"},
    {"jls95", "J-League Super Soccer '95"},
    {"jlss", "J-League Super Soccer (Virtual Soccer)"},
    {"jlwc", "Jim Lee's Wild C.A.T.S."},
    {"jm", "Joe and Mac"},
    {"jm2", "Joe and Mac 2"},
    {"jmahs", "Jissen! Mahjong Shinan"},
    {"jmf", "John Madden Football"},
    {"jmpwr", "Jim Power"},
    {"jms", "Jammes"},
    {"jng", "Jack Nicklaus Golf"},
    {"joho", "HAL's Hole in One Golf"},
    {"jojo", "Jojo no Kimyou na Bouken"},
    {"jop", "Jikkyou Oshaberi Parodius (Parodius 3)"},
    {"jot", "Jungle no Ojya Tachan"},
    {"jp", "Jurassic Park"},
    {"jp2", "Jurassic Park 2"},
    {"jph2", "Jissen Pachinko Hisshouhou! 2"},
    {"jppy3", "Jikkyou Powerful Pro Yakyuu 3"},
    {"js", "Jutei Senki"},
    {"jst", "Jungle Strike"},
    {"jstcl", "Justice League Task Force"},
    {"jumpd", "Jumpin' Derby"},
    {"jw2", "Jungle Wars 2"},
    {"ka", "Kirby's Avalanche"},
    {"kakj", "King Arthur and the Knights of Justice"},
    {"kan", "BS Gal Kan Bazooka Dai-5-Kan"},
    {"karo", "Kabuki Rocks"},
    {"kaw", "King Arthur's World"},
    {"kbgg", "Kidou Butoden G-Gundam"},
    {"kbly", "Kablooey"},
    {"kcc", "Kawasaki Caribbean Challenge"},
    {"kctgg", "Kingyo Chuihou! Tobidase Game Gakuen"},
    {"kdb", "Kunio-Kun no Dodgeball"},
    {"kdc", "Kirby's Dream Course"},
    {"kdl3", "Kirby's Dream Land 3"},
    {"kdy", "Kenyu Densetsu Yaiba"},
    {"kdz", "Kishin Douji Zenki"},
    {"kdz2", "Kishin Douji Zenki - Denei Raibu"},
    {"kdz3", "Kishin Douji Zenki 3"},
    {"keep", "Keeper"},
    {"kesp2", "Keiba Eight Special 2"},
    {"kgjb", "Ken Griffey Jr. Presents - Major League Baseball"},
    {"khb", "Koi ha Balance - Battle of Lovers"},
    {"khksc", "Katou Hifumi Kudan Shougi Club"},
    {"ki", "Killer Instinct"},
    {"kiki", "Kiki Kaikai (Pocky & Rocky)"},
    {"kiki3", "Kiki Kaikai 3 (Pocky & Rocky 2)"},
    {"kkbn", "Kerokero Keroppi no Bouken Nikki"},
    {"kkk", "Kirby's Kira Kira Kids"},
    {"kko", "Kishin Korinden Oni"},
    {"kkp", "Kidou Keisatsu Patlabor"},
    {"kkpm", "Kevin Keegan's Player Manager"},
    {"klown", "Kid Klown in Crazy Chase"},
    {"km", "King of the Monsters"},
    {"km2", "King of the Monsters 2"},
    {"kmjdo", "Kikuni Masahiko no Jantoushi Dora Ou"},
    {"kmsp", "Kindai Mahjong Special"},
    {"kmt", "Kyuuyaku Megami Tensei"},
    {"knm", "Kouryu no Mimi"},
    {"kno", "Kunio no Oden"},
    {"knoh", "BS Kirby no Omocha Hako - Baseball"},
    {"knok", "Kirby no Omochabako - Hoshi Kuzushi"},
    {"knt2", "Kawa no Nushi Tsuri 2"},
    {"kny", "Kamaitachi no Yoru"},
    {"ko", "Kick Off"},
    {"ko3", "Kick Off 3"},
    {"kod", "King of Dragons, The"},
    {"konae", "Konae-Chan no DokiDoki Pengin Kazoku"},
    {"kor", "King of Rally, The"},
    {"kotr", "Knights of the Round"},
    {"kr", "Kamen Rider"},
    {"krmt", "Kabuki-chou Reach Mahjong Tonpuu Sen"},
    {"krsd", "Kamen Rider SD - Shutsugeki!! Rider Machine"},
    {"kryk", "Kouryuuki"},
    {"ksc", "Kawasaki Superbike Challenge"},
    {"ksfh", "Krusty's Super Funhouse"},
    {"ksh", "Kakinoki Shougi"},
    {"ksn2", "Koushien 2"},
    {"ksn3", "Koushien 3"},
    {"kss", "Kirby Super Star"},
    {"kstwb", "Shigetaka Kashiwagi's Top Water Bassing"},
    {"ksvg", "Kidou Senshi V Gundam"},
    {"ktb", "Shin Nekketsu Kouha - Kunio Tachi no Bannka"},
    {"ktsz", "Kaizou Tyoujin Shubibinman Zero"},
    {"kybr", "Keiba Yosou - Baken Renkinjutsu"},
    {"lag", "Lagoon"},
    {"lah", "Last Action Hero"},
    {"lal", "Live A Live"},
    {"lambo", "Lamborghini American Challenge"},
    {"lawa", "La Wares"},
    {"lb3", "Last Bible 3"},
    {"ldst", "Lady Stalker"},
    {"leg", "Legend"},
    {"lem", "Lemmings"},
    {"lem2", "Lemmings 2"},
    {"len", "Lethal Enforcers"},
    {"lethw", "Lethal Weapon"},
    {"lft", "Last Fighter Twin"},
    {"libl", "Libble Rabble"},
    {"lifa", "Light Fantasy"},
    {"lion", "Lion King, The"},
    {"ll", "Lucky Luke"},
    {"lm", "Lord Monarch"},
    {"lmag", "Little Magic"},
    {"lmas", "Little Master"},
    {"lmm", "Lawnmower Man, The"},
    {"ln", "Paladin's Quest (Lennus)"},
    {"ln2", "Lennus 2"},
    {"lod", "Liberty or Death"},
    {"lopa", "Logos Panic"},
    {"loz3", "Legend of Zelda - A Link to the Past, The"},
    {"lrt", "Lode Runner Twin"},
    {"ltbb", "Looney Tunes Basketball"},
    {"lts", "Lodoss Tou Senki"},
    {"ltul", "Lester the Unlikely"},
    {"lunch", "Out to Lunch"},
    {"lupin", "Lupin the 3rd"},
    {"lvqst", "Love Quest"},
    {"m94", "Madden NFL '94"},
    {"m95", "Madden NFL '95"},
    {"m96", "Madden NFL '96"},
    {"m97", "Madden NFL '97"},
    {"m97gb", "Madden '97 (Super Gameboy)"},
    {"m98", "Madden NFL '98"},
    {"macs", "M.A.C.S. Basic Rifle Simulator"},
    {"magna", "Magna Braban"},
    {"mahcl", "Mahjong Club"},
    {"maj", "Majyuuou"},
    {"majt", "Mahjong Touhaiden, The"},
    {"mam", "Madou Monogatari"},
    {"mama", "Makeruna Makendou (Kendo Rage)"},
    {"mama2", "Makeruna Makendou 2"},
    {"mark", "7th Saga 2 - Mystic Ark"},
    {"marv", "Daffy Duck - The Marvin Missions"},
    {"mask", "Mask, The"},
    {"mathb", "Math Blaster - Episode One"},
    {"maui", "Maui Mallard in Cold Shadow"},
    {"mawa", "Mario & Wario"},
    {"mazz", "Mazinger Z"},
    {"mboy", "Magicboy"},
    {"mc", "Metal Combat - Falcon's Revenge"},
    {"mcdp", "Magical Drop"},
    {"mcdp2", "Magical Drop 2"},
    {"mcp", "Miracle Casino Paradise"},
    {"mcsd", "Magic Sword"},
    {"mcwr", "Mechwarrior"},
    {"mcwr3", "Mechwarrior 3050"},
    {"mdh", "Momotarou Dentetsu Happy"},
    {"mdr2", "Madara 2"},
    {"mdrs", "Youchien Senki Madara Saga"},
    {"mema", "Metal Marines"},
    {"memo", "Metal Morph"},
    {"mg", "Miracle Girls"},
    {"mgp", "Magical Pop'n"},
    {"mgt", "Mahjong Gokuu Tenjiku"},
    {"mhj", "Mohawk and Headphone Jack"},
    {"mhnr", "Mahjong Hishouden - Naki no Ryuu"},
    {"mil", "Milandra"},
    {"milk", "BS Dan Dan Belt Conveyor Milk no Maki"},
    {"mim", "Mario is Missing"},
    {"mima", "Micro Machines"},
    {"mima2", "Micro Machines 2"},
    {"mjcwc", "Michael Jordan - Chaos in the Windy City"},
    {"mjssd", "Magic Johnson's Super Slam Dunk"},
    {"mk", "Mortal Kombat"},
    {"mk2", "Mortal Kombat 2"},
    {"mk3", "Mortal Kombat 3 (Ultimate Mortal Kombat)"},
    {"mkh", "Matsumura Kunihiro Den"},
    {"mkmk", "Maka Maka"},
    {"mkr", "Mahou Kishi Reiasu (Magic Knight Rayearth)"},
    {"mlm", "Mega-Lo-Mania"},
    {"mm", "Mickey Mania - The Timeless Adventures of Mickey Mouse"},
    {"mm2", "Might and Magic 2 (European Version)"},
    {"mm2j", "Might and Magic 2 (Japanese Version)"},
    {"mm3", "Might and Magic 3"},
    {"mm7", "Mega Man 7"},
    {"mmax", "Mighty Max"},
    {"mmax2", "Metal Max 2"},
    {"mmaxr", "Metal Max Returns"},
    {"mmf", "Marko's Magic Football"},
    {"mmgg", "Mick & Mack as the Global Gladiators"},
    {"mms", "Megaman Soccer"},
    {"mmx", "Mega Man X"},
    {"mmx2", "Mega Man X2"},
    {"mmx3", "Mega Man X3"},
    {"mo2", "Earthbound (Mother 2)"},
    {"mode", "Modular Escape"},
    {"mon", "Monstania"},
    {"mono", "Monopoly (Western version)"},
    {"mp2", "Monopoly 2"},
    {"mpjp", "Monopoly (Japanese Version)"},
    {"mpm", "Ms. Pac-Man"},
    {"mpnt", "Mario Paint"},
    {"mppp", "Mahou Poi Poi Poitto!"},
    {"mq", "Magical Quest starring Mickey Mouse, The"},
    {"mq2", "Magical Quest 2 - The Great Circus Mystery, The"},
    {"mq3", "Magical Quest 3, The"},
    {"mrdo", "Mr. Do"},
    {"ms", "Melfand Stories"},
    {"msfr", "Mary Shelley's Frankenstein"},
    {"msg", "Metal Slader Glory - Director's Cut"},
    {"msp", "Mario's Super Picross"},
    {"mt", "Majin Tensei"},
    {"mt2", "Majin Tensei 2"},
    {"mtd", "Maten Densetsu"},
    {"mtm", "Mario's Time Machine"},
    {"mtma", "Magical Taruruto Kun"},
    {"mtpvb", "Multi-Play Volleyball"},
    {"muc", "Mickey's Ultimate Challenge"},
    {"mucs", "Manchester United Championship Soccer"},
    {"mulan", "Mulan (Super Gameboy)"},
    {"musya", "Gousou Jinrai Densetsu Musya (Musya - Imoto's Saga)"},
    {"mvls", "Marvelous"},
    {"mw", "Metal Warriors"},
    {"mwk", "Motoko-chan no Wonder Kitchen"},
    {"myc", "Mystery Circle"},
    {"myss", "Mini Yonku Shining Scorpion"},
    {"n517", "BS Nintendo HP 5-17"},
    {"n531", "BS Nintendo HP 5-31"},
    {"nac", "Nichibutsu Arcade Classics"},
    {"nac2", "Nichibutsu Arcade Classics 2"},
    {"nasc", "NBA All-Star Challenge"},
    {"nawo", "Naruhodo The World"},
    {"nba97", "NBA Live '97"},
    {"nba98", "NBA Live '98"},
    {"nbagg", "NBA Give 'N Go (NBA Jikkyou Basket Winning Dunk)"},
    {"nbah", "NBA Hang Time"},
    {"nbaj", "NBA Jam"},
    {"nbb", "Nobunaga no Yabou Busyo Fuunroku"},
    {"nbh", "Nobunaga no Yabou Haouden"},
    {"nbt", "Nobunaga no Yabou Tenshouki"},
    {"nbz", "Nobunaga no Yabou Zenkokuban (Nobunaga's Ambition)"},
    {"ncaaf", "NCAA Football"},
    {"ncab", "NCAA Basketball"},
    {"ncb", "Natsuki Crisis Battle"},
    {"ne", "No Escape"},
    {"neu", "Neugier"},
    {"nf", "Nosferatu"},
    {"nfb", "NFL Football"},
    {"nffb", "NCAA Final Four Basketball"},
    {"ngt", "Ninja Gaiden Triology"},
    {"nhic", "Newman-Haas Indy Car Racing"},
    {"nhlsc", "NHL Stanley Cup"},
    {"nibus", "Nightmare Busters (Beta)"},
    {"nigel", "Nigel Mansell's World Championship Racing"},
    {"nikk", "Nontan to Issyo Kuru Kuru Puzzle"},
    {"njte", "NBA Jam Tournament Edition"},
    {"nl", "Nage Libre"},
    {"nnk", "Asameshimae Nyanko"},
    {"npmp", "Nintendo Power Menu Program"},
    {"nqc", "NFL Quarterback Club"},
    {"nqc96", "NFL Quarterback Club '96"},
    {"nqr", "Network Q Rally"},
    {"nrbb", "Nolan Ryan's Baseball"},
    {"nspk", "Nangoku Syonen Papuwa Kun"},
    {"ntbh", "Nekketsu Tairiku Burning Heroes"},
    {"nump", "Numbers Paradise"},
    {"nutz", "Mr. Nutz"},
    {"nwd", "N-Warp Daisakusen"},
    {"ny", "New Yatterman"},
    {"oampg", "Okamoto Ayako to Match Play Golf"},
    {"obbf", "Ohmono Black Bass Fishing - Jinzouko Hen (Mark Davis' The Fishing Master)"},
    {"obg", "Out of Bounds Golf"},
    {"obi", "Obitus"},
    {"odanb", "Oda Nobunaga - Haou no Gundan"},
    {"oelo", "Oekaki Logic"},
    {"oeptv", "Operation Europe - Path to Victory"},
    {"off", "Super Off Road"},
    {"ogre", "Ogre Battle"},
    {"ogs", "Otogirisou"},
    {"okutg", "Super Okuman Tyoja Game"},
    {"olb", "Operation Logic Bomb"},
    {"olim", "Olivia no Mystery"},
    {"onc", "Otoboke Ninja Colosseum"},
    {"ool", "O-chan no Oekaki Logic"},
    {"oozta", "Ozumou Tamashii"},
    {"osbs", "Oraga Land Shusai"},
    {"oscar", "Oscar"},
    {"osg", "Olympic Summer Games"},
    {"osggb", "Olympic Summer Games (Super Gameboy)"},
    {"othnd", "Operation Thunderbolt"},
    {"othw", "Othello World"},
    {"otk", "Ongaku Tukuoolu Kanadeeru"},
    {"otld", "Outlander"},
    {"paca", "Pac-Attack"},
    {"pacm2", "Pac-Man 2 - The New Adventures"},
    {"page", "Pagemaster"},
    {"pam", "Packy and Marlon"},
    {"pbgl", "Pebble Beach Golf Links"},
    {"pd", "Parodius Da!"},
    {"pdw", "Pirates of Dark Water"},
    {"peye", "Popeye - Ijiwaru Majo Sea Hag No Maki"},
    {"pfma", "Pitfall - The Mayan Adventure"},
    {"pga96", "PGA Tour '96"},
    {"pgae", "PGA European Tour"},
    {"pgat", "PGA Tour Golf"},
    {"phant","Phantom 2040"},
    {"phlnx", "Phalanx"},
    {"pi", "Power Instinct"},
    {"piece", "Pieces (Jigsaw Party)"},
    {"piggs", "Power Piggs of the Dark Ages"},
    {"piki", "Pikiinya!"},
    {"pink", "Pink Goes to Hollywood"},
    {"pino", "Pinocchio"},
    {"pipe", "Pipe Dream"},
    {"pkn", "Poko-Nyan!"},
    {"plok", "Plok!"},
    {"plr", "Power Lode Runner"},
    {"pman", "Prehistorik Man"},
    {"pmh", "Pachinko Maruhi Hisshouhou"},
    {"pmk", "Pro Mahjong Kiwame"},
    {"pmk2", "Pro Mahjong Kiwame 2"},
    {"pmk3", "Pro Mahjong Kiwame 3"},
    {"pmkgb", "Pro Mahjong Kiwame GB (Super Gameboy)"},
    {"pms", "Parlor! Mini series (BGM Compilation)"},
    {"pmv", "Power Moves"},
    {"pns", "Pop'n Smash!!"},
    {"pnt", "Pac-in-Time"},
    {"pntb", "Pop 'n' Twinbee"},
    {"pnyd", "Poko-Nyan! Yume no Daibouken (Super Gameboy)"},
    {"pnyw", "Panic in Nakayoshi World"},
    {"poca", "Pocahontas (Super Gameboy)"},
    {"poke", "BS Pokekame Magajin"},
    {"pop", "Prince of Persia"},
    {"pop2", "Prince of Persia 2"},
    {"popfm", "Popful Mail"},
    {"poth", "Power of the Hired"},
    {"pow94", "Jikkyou Powerful Pro Yakyuu '94"},
    {"powdr", "Power Drive"},
    {"pp", "Kyouraku Sanyou Toyomaru Parlor Parlor!"},
    {"pp2", "Kyouraku Sanyou Toyomaru Daiichi Maruhon Parlor Parlor! 2"},
    {"pp3", "Kyouraku Sanyou Toyomaru Okumura Taiyou Parlor Parlor! 3"},
    {"pp4", "Kyouraku Sanyou Toyomaru Okumura Daiichi Maruhon Parlor Parlor! 4 CR"},
    {"pp5", "Kyouraku Sanyou Maruhon Parlor Parlor! 5"},
    {"pph", "Popoitto Hebereke"},
    {"pphh", "Porky Pig's Haunted Holiday"},
    {"ppl", "Populous"},
    {"ppnw", "Poi Poi Ninja World"},
    {"pr", "Power Rangers"},
    {"prage", "Primal Rage"},
    {"prfe", "Power Rangers - The Fighting Edition"},
    {"prime", "Prime"},
    {"prmn", "Princess Minerva"},
    {"prmv", "Mighty Morphin' Power Rangers - The Movie"},
    {"proq", "Pro Quarterback"},
    {"prt", "Pachinko Renchan Tengoku - Super CR Special"},
    {"prz", "Power Rangers Zeo - Battle Racers"},
    {"psfx", "Power Slide FX"},
    {"psh", "Pro Sport Hockey"},
    {"psq", "Putty Squad"},
    {"psycho", "Psycho Dream"},
    {"ptss", "Pachinko Tetsujin - Shichiban Shoubu"},
    {"ptws", "Pilotwings"},
    {"pubo", "Puzzle Bobble (Bust-A-Move)"},
    {"push", "Pushover"},
    {"pwrmg", "Powermonger"},
    {"pynps", "Pro Yakyuu Nettou Puzzle Stadium"},
    {"qb3", "Q-bert 3"},
    {"r2", "Rendering Ranger"},
    {"raced", "Race Drivin'"},
    {"ramp", "Rampart"},
    {"rapbb", "Rap Basketball"},
    {"rarm", "Ruin Arm"},
    {"rbb", "Riddick Bowe Boxing"},
    {"rbi", "Super RBI Baseball"},
    {"rbs", "Rushing Beat Syura (Peace Keepers)"},
    {"rckf", "Rockfall"},
    {"rcmb", "Roger Clemens' MVP Baseball"},
    {"rcop3", "Robocop 3"},
    {"rd", "Radical Dreamers"},
    {"rdn", "Raiden Densetsu"},
    {"realm", "Realm"},
    {"revx", "Revolution X"},
    {"rf", "Rockman and Forte (Megaman and Bass)"},
    {"rhdz", "Ryukiheidan Danzarubu"},
    {"rhi95", "RHI Roller Hockey '95"},
    {"ring", "Boxing Legends of the Ring"},
    {"rival", "Rival Turf"},
    {"rj", "Rap Jam"},
    {"rjc", "Rejoice - Aretha Oukoku no Kanata"},
    {"rk", "Riverse Kids"},
    {"rkdb", "Rokudenashi Blues"},
    {"rmath", "Ranma 1-2 - Akaneko-dan Teki Hihou"},
    {"rmbr", "Ranma 1-2 - Bakuretsu Rantouhen"},
    {"rmcg", "Ranma Nibunnoichi - Chonai Gekitou Hen"},
    {"rmk", "RPG Maker"},
    {"rmk2", "RPG Maker 2"},
    {"rml", "Rocko's Modern Life - Spunky's Dangerous Day"},
    {"rmoj", "Ranma Nibunnoichi - Ougi Jaanken"},
    {"rnh", "Rudra no Hihou"},
    {"rnk", "Art of Fighting"},
    {"rnk2", "Ryuuko no Ken 2 (Art of Fighting 2)"},
    {"rnsb", "Ren & Stimpy - Buckeroo$"},
    {"rodd", "Return of Double Dragon"},
    {"rotr", "Rise of the Robots"},
    {"rpmr", "RPM Racing"},
    {"rr4w", "Road Riot 4WD"},
    {"rres", "Rex Ronan"},
    {"rrex", "Radical Rex"},
    {"rrod", "Rocky Rodent"},
    {"rrr", "Rock 'n' Roll Racing"},
    {"rs", "Romancing SaGa"},
    {"rs2", "Romancing SaGa 2"},
    {"rs3", "Romancing SaGa 3"},
    {"rstw", "Ren and Stimpy - Time Warp"},
    {"rt", "Rocketeer"},
    {"rt3", "R-Type 3"},
    {"rtk2", "Super Romance of the Three Kingdoms 2 (Super Sangokushi 2)"},
    {"rtk3", "Sangokushi 3 (Romance of the Three Kingdoms 3)"},
    {"rtk4", "Sangokushi 4 (Romance of the Three Kingdoms 4)"},
    {"rtrek", "Robotrek"},
    {"run", "Run Saber"},
    {"rvt", "Robocop vs. the Terminator"},
    {"s8h", "Suzuka 8 Hours"},
    {"sa", "Super Aleste (Space Megaforce)"},
    {"sace", "Space Ace"},
    {"sad", "Super Air Diver"},
    {"sad2", "Super Air Diver 2"},
    {"saf", "Skipp and Friends"},
    {"sai", "Super Adventure Island"},
    {"sai2", "Super Adventure Island 2"},
    {"same", "Same Game"},
    {"samu", "Samurai Shodown"},
    {"sana2", "Sansara Naga 2"},
    {"sans", "Sanrio Shanghai"},
    {"sate", "BS SatesupuDX 4"},
    {"saxar", "Spiderman and the X-Men - Arcade's Revenge"},
    {"sb", "Soul Blazer"},
    {"sb2", "Super Big 2"},
    {"sb20", "Super Baseball 2020"},
    {"sbb", "Super Buster Bros."},
    {"sbb1", "Super Black Bass"},
    {"sbb2", "Super Black Bass 2 (Bassin's Black Bass)"},
    {"sbc", "Shien - The Blade Chaser (Shien's Revenge)"},
    {"sbf2", "Super Back to the Future 2"},
    {"sbk", "Super Bikkuriman"},
    {"sbl", "Super Bases Loaded"},
    {"sbl2", "Super Bases Loaded 2"},
    {"sbl3", "Super Bases Loaded 3"},
    {"sblm", "Sonic Blastman"},
    {"sblm2", "Sonic Blastman 2"},
    {"sbm", "Super Bomberman"},
    {"sbm2", "Super Bomberman 2"},
    {"sbm3", "Super Bomberman 3"},
    {"sbm4", "Super Bomberman 4"},
    {"sbm5", "Super Bomberman 5"},
    {"sbn", "Simpsons - Bart's Nightmare, The"},
    {"sbom", "Super Bombliss"},
    {"sbowl", "Super Bowling"},
    {"sbr2", "Syutoko Battle Racing 2"},
    {"sbs", "Super Battleship"},
    {"sbtk", "Super Battletank"},
    {"sbtk2", "Super Battletank 2"},
    {"sbup", "Super Batter Up"},
    {"sc", "Sim City"},
    {"scas2", "Super Casino 2"},
    {"scd", "Scooby Doo Mysteries"},
    {"schq", "Super Chase H.Q."},
    {"sck", "Shin Chou Kouki"},
    {"scme", "Super Conflict - The Mideast"},
    {"scp", "Super Caesar's Palace"},
    {"scv4", "Super Castlevania 4"},
    {"sd2", "Secret of Mana"},
    {"sd3", "Seiken Densetsu 3"},
    {"sdd", "Super Double Dragon"},
    {"sdf1g", "SD F-1 Grand Prix"},
    {"sdg2", "SD Gundam 2"},
    {"sdgb", "SD Great Battle"},
    {"sdgg", "SD Gundam Gaiden - Knight Gundam Monogatari Ooinaru Isan"},
    {"sdgg2", "SD Gundam Gaiden 2 - Entaku no Kishi"},
    {"sdggn", "SD Gundam G-Next"},
    {"sdggx", "SD Gundam GX"},
    {"sdgpf", "SD Gundam Power Formation Puzzle"},
    {"sdgv", "SD Kidou Senshi Gundam V"},
    {"sdgx", "SD Gundam X - Super Gachapon World"},
    {"sdhk", "SD Hiryu no Ken"},
    {"sdmc", "Sword Maniac"},
    {"sdo", "Super Drift Out"},
    {"sdpf", "Seifuku Densetsu - Pretty Fighter"},
    {"sdub", "SD Ultra Battle"},
    {"sduns", "Super Dunk Star"},
    {"se", "Sim Earth"},
    {"sens", "Sensible Soccer"},
    {"sesb", "Super Star Wars - The Empire Strikes Back"},
    {"sf", "Star Fox"},
    {"sf1c", "Super F1 Circus"},
    {"sf1h", "Super F1 Hero"},
    {"sf2", "Street Fighter 2"},
    {"sf2t", "Street Fighter 2 Turbo"},
    {"sfa2", "Street Fighter Alpha 2"},
    {"sfb", "Space Football"},
    {"sfc", "Super Family Circuit"},
    {"sfcb", "Super Famicom Box BIOS"},
    {"sfcw", "Super Famicom Wars"},
    {"sff", "Sankyou Fever Fever!"},
    {"sfg", "Super Family Gerende"},
    {"sfmt", "Super Final Match Tennis"},
    {"sfpw", "Super Fire Pro Wrestling"},
    {"sfs", "Super Formation Soccer (Super Soccer)"},
    {"sfs2", "Super Formation Soccer 2"},
    {"sfs94", "Super Formation Soccer '94"},
    {"sfs95", "Super Formation Soccer '95"},
    {"sfs96", "Super Formation Soccer '96"},
    {"sft", "Super Family Tennis"},
    {"sftr", "Starfield Trainer"},
    {"sfx2", "Star Fox 2 (never released to public)"},
    {"sg10g", "St. Giga 10gatsu Gou"},
    {"sg3", "Shinri Game 3, The"},
    {"sgate", "Stargate"},
    {"sgb", "Super Gameboy"},
    {"sgb2", "Super Gameboy 2"},
    {"sgd", "Sengoku Denshou"},
    {"sggb", "Speedy Gonzalez in Los Gatos Banditos"},
    {"sgh", "Sugoi Hebereke"},
    {"sgj2", "Super Genjin 2"},
    {"sgm", "Same Game Mario"},
    {"sgn", "Super Gomoku Narabe Renju"},
    {"sgng", "Super Ghouls 'n' Ghosts"},
    {"sgo", "Super Gussun Oyoyo"},
    {"sgo2", "Super Gussun Oyoyo 2"},
    {"sgoal", "Super Goal!"},
    {"sgod", "Super Godzilla"},
    {"sh94", "Super Hockey '94"},
    {"sh95", "Street Hockey '95"},
    {"shad", "Shadow, The"},
    {"shaq", "Shaq Fu"},
    {"shas", "Shonen Ashibe"},
    {"shed", "Shiki Eiyuu Den - Jinryuu Densetsu"},
    {"shg", "Shanghai - Banri no Tyojyo ~ The Great Wall"},
    {"shg2", "Shanghai 2 - Dragon's Eye"},
    {"shgc", "Shougi Club"},
    {"shgfk", "Shougi Fuurinkazan"},
    {"shi", "Super High Impact"},
    {"shod", "Shinseiki Odysselya"},
    {"shod2", "Shinseiki Odysselya 2"},
    {"shr", "Shadowrun"},
    {"shsa", "Shougi Saikyou"},
    {"shuso", "Sailor Moon Super S - Zenin Sanka!! Shuyaku Soudatsusen"},
    {"si", "Space Invaders"},
    {"sic", "Super International Cricket"},
    {"sicfb", "Sports Illustrated Championship Football and Baseball"},
    {"sidep", "Side Pocket"},
    {"sima", "SimAnt"},
    {"sindc", "Super Indy Champ"},
    {"sis", "Shin Ikkaku Senkin"},
    {"sisgb", "Space Invaders (Super Game Boy)"},
    {"sjp", "Super James Pond"},
    {"sjp2", "Super James Pond 2"},
    {"sjp3", "Super James Pond 3"},
    {"sk", "SWAT Kats"},
    {"skab", "Sougou Kakutougi Astral Bout"},
    {"skab2", "Sougou Kakutougi Astral Bout 2 - The Total Fighters"},
    {"skab3", "Astral Bout 3"},
    {"skb", "Skyblazer"},
    {"skh", "Sengo Kuno Hasha - Tenka Fubu heno Michi"},
    {"skhs", "Super Kyuukyoku Harikiri Stadium"},
    {"skjg", "Skuljagger"},
    {"skyin", "Super Koukou Yakyuu - Ikkyuu Nyuukon"},
    {"slap", "Super Slapshot"},
    {"slay", "Slayers"},
    {"sloop", "Super Loopz"},
    {"sm", "Super Metroid"},
    {"smadc", "Super Mad Champ"},
    {"smas", "Super Mario All-Stars"},
    {"smbb", "Seijuu Maden - Beasts & Blades"},
    {"smd", "Shin Momotarou Densetsu"},
    {"smdd", "Super Momotarou Dentetsu DX"},
    {"smeb", "Super Mario Excitebike"},
    {"smffp", "Sailor Moon Super S - Fuwa Fuwa Panic"},
    {"smk", "Super Mario Kart"},
    {"smlf", "Spiderman - Lethal Foes"},
    {"smoon", "Sailor Moon - Another Story"},
    {"smph", "Super Morph"},
    {"smr", "Super Mario RPG"},
    {"smsh", "Shodan Morita Shougi"},
    {"smsjr", "Bishoujo Senshi Sailormoon S - Jougai Rantou"},
    {"smsk", "Sailor Moon S - Kurukkurin"},
    {"smso", "Small Soldiers (Super Gameboy)"},
    {"smspo", "Bishoujo Senshi Sailormoon S - Kondoha Puzzle de Oshiokiyo!"},
    {"smsv", "Shooting Macross - Scrambled Valkyrie"},
    {"smt", "Shin Megami Tensei"},
    {"smt2", "Shin Megami Tensei 2"},
    {"smti", "Shin Megami Tensei - If..."},
    {"smurf", "Smurfs, The"},
    {"smurf2", "Smurfs 2, The"},
    {"smw", "Super Mario World"},
    {"snb", "Super Ninja Boy"},
    {"snbb", "Sporting News Baseball"},
    {"snbt", "Mecarobot Golf"},
    {"snc", "Snoopy Concert"},
    {"sngks", "Super Sangokushi (Super Romance of the Three Kingdoms)"},
    {"snk", "Super Ninja Kun"},
    {"snkk", "Shodai Nekketsu Kouha Kunio-Kun"},
    {"sno", "Super Naxat Open"},
    {"snpw", "Shin Nippon Pro Wrestling - Chou Senshi in Tokyo Dome"},
    {"sns", "Shonen Ninja Sasuke"},
    {"snsm", "Saturday Night Slam Masters"},
    {"snspm", "Shodankurai Nintei Shodan Pro Mahjong"},
    {"snt", "Sound Novel Tsukuru"},
    {"snw94", "Shin Nihon Pro Wrestling '94"},
    {"snz", "Super Nazo Puyo - Rulue no Roux"},
    {"snz2", "Super Nazo Puyo 2 - Rulue no Tetsuwan Hanjyou Ki"},
    {"so", "Star Ocean"},
    {"soe", "Secret of Evermore"},
    {"sof", "Soldiers of Fortune"},
    {"sokid", "Soccer Kid"},
    {"solid", "Solid Runner"},
    {"son", "Heisei Shin Onigashima"},
    {"sond", "Super Oozumou Netsusen Daiichiban"},
    {"song", "Song Master"},
    {"sortb", "Super Off Road - The Baja"},
    {"sos", "S.O.S."},
    {"sosw", "Sink or Swim"},
    {"sotb", "Shadow of the Beast"},
    {"sots", "Tecmo Secret of the Stars"},
    {"soulb", "Soul Blade (Pirate)"},
    {"sp", "Bishoujo Janshi Suuchiipai"},
    {"sp2", "Super Puyo Puyo 2"},
    {"sp2r", "Super Puyo Puyo 2 Remix"},
    {"spach", "Super Pachinko"},
    {"spaf", "Super Play Action Football"},
    {"spark", "Sparkster"},
    {"spata", "Super Pachinko Taisen"},
    {"spb2", "Super Professional Baseball 2"},
    {"spbtm", "Super Pinball - Behind the Mask"},
    {"spbw", "Super Bomberman - Panic Bomber W"},
    {"spc", "Spellcraft"},
    {"spdz", "Spindizzy Worlds"},
    {"spec", "Spectre"},
    {"speed", "Speed Racer"},
    {"spir", "Spirou"},
    {"spl", "Super Power League"},
    {"spl2", "Super Power League 2"},
    {"spl3", "Super Power League 3"},
    {"spl4", "Super Power League 4"},
    {"spm", "Spider-Man"},
    {"spn", "Supapoon"},
    {"spndx", "Supapoon DX"},
    {"spo", "Super Punch-Out!!"},
    {"spp", "Super Puyo Puyo"},
    {"sprp", "Spriggan Powered"},
    {"spt", "Super Putty"},
    {"spw", "Spark World"},
    {"spwn", "Spawn"},
    {"sqdsv", "SeaQuest DSV"},
    {"srace", "Street Racer"},
    {"srb", "Super Royal Blood (Gemfire)"},
    {"srmh", "Saibara Rieko no Mahjong Hourouki"},
    {"srt", "Super R-Type"},
    {"srt3", "Super Robot Taisen 3"},
    {"srt4", "Super Robot Taisen 4"},
    {"srte", "Super Robot Taisen EX"},
    {"srtg", "Super Robot Taisen Gaiden - Masoukishin - The Lord of Elemental"},
    {"srtj", "Super Star Wars - Return of the Jedi"},
    {"srtls", "Shiroi Ring he - Twinkle Little Star"},
    {"ss2", "Silva Saga 2"},
    {"ss6", "Super Scope 6"},
    {"ssc", "Super Soccer Champ"},
    {"ssds", "Shin SD Sengokuden - Daishougun Retsuden"},
    {"sse", "Super Strike Eagle"},
    {"sse2e", "Sterling Sharpe - End 2 End"},
    {"ssf2", "Super Street Fighter 2"},
    {"sshg", "Super Shougi"},
    {"sshg2", "Super Shougi 2"},
    {"sshg3", "Super Shougi 3"},
    {"sshgc", "Shin Shougi Club"},
    {"ssitfo", "Steven Seagal is the Final Option"},
    {"sslsa", "Shijou Saikyou League Serie A - Ace Striker"},
    {"ssnqs", "Shijou Saikyou no Quiz Ou Kettei Sen Super"},
    {"ssou", "Super Soukoban"},
    {"ssrd", "Sunset Riders"},
    {"sssm", "Saikousoku Shikou Shougi Mahjong"},
    {"ssta", "Super Stadium"},
    {"sstbs", "Tenbu Spirits"},
    {"ssw", "Super Star Wars"},
    {"sswap", "BS Sousa Sentai Wappers"},
    {"st2", "Super Tetris 2 + Bombliss"},
    {"st2l", "Super Tetris 2 + Bombliss Limited Edition"},
    {"st3", "Super Tetris 3"},
    {"stc", "Super Trump Collection"},
    {"sten", "Super Tennis"},
    {"stf", "Super Tekkyu Fight!"},
    {"stg", "Strike Gunner STG"},
    {"sth", "Sutte Hakkun"},
    {"sti", "Super Troll Islands"},
    {"stl", "Stealth"},
    {"stn", "Star Trek - The Next Generation"},
    {"stone", "Stone Protectors"},
    {"strc", "Street Combat"},
    {"strkr", "Striker"},
    {"sts", "Special Tee Shot"},
    {"stsfa", "Star Trek - Starfleet Academy - Ship Bridge Simulator"},
    {"stsh", "Super Tsume Shougi 1000"},
    {"stv", "Super Smash TV"},
    {"sub2", "Super Ultra Baseball 2"},
    {"suco", "Super Copa"},
    {"sudy", "Super Double Yakuman"},
    {"sudy2", "Super Double Yakuman 2"},
    {"sufa", "Super Famista"},
    {"sufa2", "Super Famista 2"},
    {"suftu", "Sufami Turbo BIOS"},
    {"suha", "Super Hanafuda"},
    {"sumj", "Super Mahjong"},
    {"sumj2", "Super Mahjong 2"},
    {"sumj3", "Super Mahjong 3"},
    {"sumt", "Super Mahjong Taikai"},
    {"suno", "Super Uno"},
    {"suso", "Super Solitaire"},
    {"sv4", "Super Valis 4"},
    {"svb", "Onizuka Katsuya Super Virtual Boxing"},
    {"svg", "Super Variable Geo"},
    {"svln", "Syvalion"},
    {"svmc", "Spider-Man and Venom - Maximum Carnage"},
    {"svsa", "Spider-Man & Venom - Separation Anxiety"},
    {"sw", "Sonic Wings"},
    {"swc", "Super Wild Card"},
    {"swdg", "Super Widget"},
    {"swhea", "Snow White - Happily Ever After"},
    {"swiv", "Super Swiv"},
    {"sws", "Sword World SFC"},
    {"sws2", "Sword World SFC 2"},
    {"swsb", "Sanrio World Smash Ball"},
    {"syaro", "Sutobasu Yarou Show - 3 on 3 Basketball"},
    {"syl", "Shoot Your Load"},
    {"syn", "Syndicate"},
    {"syobo", "Super Syobo Syobo CG Collection"},
    {"syti", "Shounin yo, Taishi o Idake!!"},
    {"sz", "Super Zugan"},
    {"sz2", "Super Zugan 2"},
    {"t2jd", "Terminator 2 - Judgment Day"},
    {"t2tag", "T2 - The Arcade Game"},
    {"ta", "Tetris Attack (Panel de Pon)"},
    {"tamo", "Waratte Iitomo! Tamorinpic"},
    {"tanf", "Troy Aikman NFL Football"},
    {"tarm", "Tarot Mystery"},
    {"taso", "Tactical Soccer"},
    {"taz", "Taz-Mania"},
    {"tb2", "Thoroughbred Breeder 2"},
    {"tb3", "Thoroughbred Breeder 3"},
    {"tbat", "Tetris Battle Gaiden"},
    {"tbgmd", "Table Game Daishuugou!"},
    {"tbnfz", "Turn and Burn - No Fly Zone"},
    {"tcar", "Total Carnage"},
    {"tcx", "Treasure Conflix"},
    {"tdl", "Mickey no Tokyo Disneyland Daibouken"},
    {"tdm", "Tetris and Dr. Mario"},
    {"tdsp", "Thunder Spirits"},
    {"temu", "Tenchi Muyo"},
    {"test", "SNES Test Program"},
    {"tet2", "Tetris 2"},
    {"tg", "Top Gear"},
    {"tg2", "Top Gear 2"},
    {"tg3", "Top Gear 3000"},
    {"thbi", "Thunderbirds"},
    {"thead", "Tinhead"},
    {"thg", "Treasure Hunter G"},
    {"tick", "Tick, The"},
    {"tii", "Taikyoku Igo Idaten"},
    {"timec", "Time Cop"},
    {"tit", "Teenage Mutant Ninja Turtles IV - Turtles in Time"},
    {"tj", "Tom and Jerry"},
    {"tkd", "Taekwon-Do"},
    {"tkj", "Tekichuu Keiba Juku"},
    {"tkmm", "Tokimeki Memorial"},
    {"tko", "TKO Super Championship Boxing"},
    {"tkrm", "Tokoro's Mahjong"},
    {"tkrsd", "Taikou Rissiden"},
    {"tl", "True Lies"},
    {"tlb", "Last Battle, The"},
    {"tlm", "Tottemo! Lucky Man"},
    {"tm2", "Top Management 2"},
    {"tmkit", "Takemiya Masaki Kudan no Igo Taishou"},
    {"tmnt5", "Teenage Mutant Ninja Turtles - Tournament Fighters"},
    {"tmss", "Tony Meola's Sidekicks Soccer"},
    {"tnd", "Torneco no Daibouken - Fushigi no Dungeon"},
    {"tnk", "Teitoku no Ketsudan"},
    {"tnk2", "Teitoku no Ketsudan 2"},
    {"tnu", "Tenshi no Uta - Shiroki Tsubasa no Inori"},
    {"tnw", "Ninja Warriors, The"},
    {"to", "Tactics Ogre"},
    {"top", "Tales of Phantasia"},
    {"torsh", "Tsuppari Oozumo Rissin Shusse Hen"},
    {"totf", "Total Football"},
    {"toys", "Toys"},
    {"tp", "Theme Park"},
    {"tpjg", "Timon and Pumbaa's Jungle Games"},
    {"trba", "Twinbee - Rainbow Bell Adventure"},
    {"trin", "Trinea"},
    {"trod", "Troddlers"},
    {"ts", "Terranigma"},
    {"tsb", "Tecmo Super Baseball"},
    {"tsbw", "Tecmo Super Bowl"},
    {"tsg", "Shinri Game, The"},
    {"tsg2", "Shinri Game 2 - Magical Trip, The"},
    {"tslip", "Time Slip"},
    {"tsnb", "Tecmo Super NBA Basketball"},
    {"tsp", "Traverse - Starlight and Prairie"},
    {"tst", "Toy Story"},
    {"tstar", "Tin Star"},
    {"tstgb", "Toy Story (Super Gameboy)"},
    {"tstp", "Tsuyoshi Shikkarishinasai Taisen Puzzle-Dama"},
    {"tsuta", "Tsuri Taro"},
    {"tta", "Tiny Toon Adventures - Buster Busts Loose"},
    {"ttat", "TinTin au Tibet"},
    {"ttawsc", "Tiny Toon Adventures - Wacky Sports Challenge"},
    {"ttef", "Thomas the Tank Engine & Friends"},
    {"ttsmf", "Twisted Tales of Spike McFang, The"},
    {"ttts", "TinTin, Les Aventures de - Le Temple du Solei"},
    {"ttx", "Time Trax"},
    {"tuff", "Mr. Tuff"},
    {"turr", "Super Turrican"},
    {"turr2", "Super Turrican 2"},
    {"twa", "Tetsuwan Atom"},
    {"tybo", "Tadaima Yusya Bosyutyu Okawari"},
    {"u7", "Ultra Seven"},
    {"ubj", "Ultra Baseball Jitsumeiban"},
    {"ubj2", "Ultra Baseball Jitsumeiban 2"},
    {"ubj3", "Ultra Baseball Jitsumeiban 3"},
    {"ucc", "Undercover Cops"},
    {"ukt", "Ultima - Dinosaur Empire"},
    {"uktb", "Utyu no Kishi Tekkaman Blade"},
    {"ulmst", "Ultra League"},
    {"ult6", "Ultima 6"},
    {"ult7", "Ultima 7"},
    {"ultm", "Ultraman"},
    {"um", "Ultraman - Towards the Future"},
    {"umi", "Umihara Kawase"},
    {"umizm", "Umizuri Meijin"},
    {"unfl", "Untitled NFL Football Game"},
    {"unir", "Uniracers"},
    {"unt", "Untouchables, The"},
    {"urov2", "Ultima - Runes of Virtue 2"},
    {"us", "Urban Strike"},
    {"usol", "Universal Soldier"},
    {"ut", "Ushio and Tora"},
    {"uto", "Utopia"},
    {"uw", "Super Dai Koukai Jidai (Super Unchartered Water)"},
    {"uw2", "Dai Koukai Jidai 2 (Uncharted Waters - New Horizons)"},
    {"vbart", "Virtual Bart"},
    {"vbt", "Volleyball Twin"},
    {"vegas", "Vegas Stakes"},
    {"vewo", "Verne World"},
    {"vill", "Kouryuu Densetsu Villgust"},
    {"voh", "Violinist of Hameln"},
    {"vor", "Vortex"},
    {"vsc", "Vs. Collection"},
    {"vt", "Soukoukihei Votoms - The Battling Road"},
    {"w2410", "War 2410"},
    {"w2ah", "Wings 2 Aces High"},
    {"w3010", "War 3010"},
    {"waia", "Waialae Country Club"},
    {"wally", "Wally wo Sagase"},
    {"wapa", "BS Wapaaz Souryu Hen"},
    {"warl", "Warlock"},
    {"warp", "WarpSpeed"},
    {"wawo", "Waterworld"},
    {"wc", "Wing Commander"},
    {"wc98", "Wrecking Crew '98"},
    {"wcr", "World Class Rugby"},
    {"wcu94", "World Cup USA '94"},
    {"wcup", "World Cup '98 (Super Gameboy)"},
    {"wcwsb", "WCW SuperBrawl Wrestling"},
    {"wedp", "Wedding Peach"},
    {"wesas", "Winter Extreme - Skiing and Snowboarding"},
    {"wfdx", "Wheel of Fortune - Deluxe Edition"},
    {"wgfx", "Winter Gold FX"},
    {"wgl", "Super Wagan Land"},
    {"wgnhl", "Wayne Gretzky and the NHLPA All-Stars"},
    {"wgp", "Wagyan Paradise"},
    {"wguns", "Wild Guns"},
    {"wh", "World Heroes"},
    {"wh2", "World Heroes 2"},
    {"whizz", "Whizz"},
    {"whrl", "Whirlo"},
    {"wiz123", "Wizardry 1-2-3"},
    {"wiz5", "Wizardry 5 - Heart of the Maelstrom"},
    {"wiz6", "Wizardry VI"},
    {"wizg4", "Wizardry Gaiden IV"},
    {"wl", "WeaponLord"},
    {"wls", "World League Soccer"},
    {"wmg", "World Masters Golf"},
    {"wnrn", "Ken Griffey Jr. Winning Run"},
    {"woar", "Wolverine - Adamantium Rage"},
    {"wog", "Winter Olympic Games"},
    {"wolf", "Wolf Child"},
    {"wom", "World of Manga II"},
    {"wonm", "Wondrous Magic"},
    {"word", "Wordtris"},
    {"worms", "Worms"},
    {"wotg", "War of the Gems"},
    {"woz", "Wizard of Oz"},
    {"wozz", "Chou Mahou Tairiku Wozz"},
    {"wpj", "Wonder Project J"},
    {"wsnk", "WildSnake"},
    {"wt", "Stunt Race FX"},
    {"wtoz", "Wakataka Oozumou"},
    {"wwfa", "WWF Wrestlemania - The Arcade Game"},
    {"wwfr", "WWF Raw"},
    {"wwfrr", "WWF Royal Rumble"},
    {"wwfsw", "WWF Super Wrestlemania"},
    {"wws", "Waku Waku Ski Wonder Shoot"},
    {"xak", "Xak - The Art of Visual Stage"},
    {"xband", "XBand Modem"},
    {"xkb", "X-Kaliber 2097"},
    {"xma", "X-Men - Mutant Apocalypse"},
    {"xmas", "Christmas Craze"},
    {"xmvsf", "X-Men vs. Street Fighter (Pirate)"},
    {"xrdn", "Xardion"},
    {"xz", "X-Zone"},
    {"yaki", "UFO Kamen Yakisoban"},
    {"yc", "Yoshi's Cookie"},
    {"yi", "Super Mario World 2 - Yoshi's Island"},
    {"yjjg", "Yuujin Janjuu Gakuen"},
    {"ykb", "Youkai Buster - Ruka no Daibouken"},
    {"ykc", "Yakouchuu"},
    {"ym", "Young Merlin"},
    {"ymng", "Yume Maboroshi no Gotoku"},
    {"ynffg", "Yuujin no Furi Furi Girls"},
    {"ynk", "Yoshi no Kuruppon"},
    {"yogi", "Yogi Bear"},
    {"yqgg", "Yuuyu no Quiz de Go! Go!"},
    {"ys3", "Ys 3 - Wanderers From Ys"},
    {"ys4", "Ys IV - Mask of the Sun"},
    {"ys5", "Ys 5"},
    {"ysfr", "Yoshi's Safari"},
    {"ytak", "Yamato Takeru"},
    {"ywd", "Yadamon Wonderland Dreams"},
    {"yyh", "Yuu Yuu Hakusho"},
    {"yyh2", "Yuu Yuu Hakusho 2"},
    {"yyht", "Yuu Yuu Hakusho - Tokubetsu-hen"},
    {"z4cr", "Zero 4 Champ RR"},
    {"zamn", "Zombies Ate My Neighbors"},
    {"zan2", "Zan 2 Spirits"},
    {"zan3", "Zan 3 Spirits"},
    {"zgd", "Z-Gundam - Away to the Newtype"},
    {"zgts", "Zen Nihon GT Sensyuken"},
    {"zico", "Zico Soccer"},
    {"zjsg", "Zenkoku Juudan Ultra Shinri Game"},
    {"zks", "Zero the Kamikaze Squirrel"},
    {"zkss", "'96 Zenkoku Koukou Soccer Senshuken"},
    {"zkss2", "Zenkoku Koukou Soccer Senshuken 2"},
    {"zkssh", "Zenkoku Koukou Soccer Senshuken"},
    {"zna", "Zakuro no Aji"},
    {"znpw", "Zennihon Pro Wrestling"},
    {"znpw2", "Zennihon Pro Wrestling 2 - 3.4 Budoukan"},
    {"znpwd", "Zennihon Pro Wrestling Dash - Sekai Saikyou Tag (Natsume Championship Wrestling)"},
    {"zone", "Zone"},
    {"zool", "Zool"},
    {"zoop", "Zoop"},
    {"zoot", "Zootto Mahjong!"},
    {"zzc", "Zig Zag Cat"},
};

#define RSN_NAMES_COUNT (sizeof(rsn_names) / sizeof(rsn_names[0]))


int snes_spc_entries=sizeof(SNESmusic_names)/sizeof(rsn_name_mapping_t);
